// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type ControllerCreate = {
    /**
     * Controller name, e.g. 'fan', 'heater'
     */
    name: string;
    model?: (string | null);
    greenhouse_id: string;
};

export type ControllerPublic = {
    /**
     * Controller name, e.g. 'fan', 'heater'
     */
    name: string;
    model?: (string | null);
    id: string;
    greenhouse_id: string;
};

export type ControllerUpdate = {
    name?: (string | null);
    model?: (string | null);
};

export type CropCreate = {
    /**
     * Name of the crop (e.g., 'Tomato')
     */
    name: string;
    description?: (string | null);
    /**
     * Expected yield per square meter
     */
    expected_yield_per_sqm?: (number | null);
    /**
     * Expected days from seed to harvest
     */
    growing_days?: (number | null);
    recipe?: ({
    [key: string]: unknown;
} | null);
};

export type CropPublic = {
    /**
     * Name of the crop (e.g., 'Tomato')
     */
    name: string;
    description?: (string | null);
    /**
     * Expected yield per square meter
     */
    expected_yield_per_sqm?: (number | null);
    /**
     * Expected days from seed to harvest
     */
    growing_days?: (number | null);
    id: string;
    recipe?: ({
    [key: string]: unknown;
} | null);
};

export type CropUpdate = {
    name?: (string | null);
    description?: (string | null);
    recipe?: ({
    [key: string]: unknown;
} | null);
    expected_yield_per_sqm?: (number | null);
    growing_days?: (number | null);
};

export type GreenhouseClimateRead = {
    temperature: number;
    humidity: number;
    outside_temperature: number;
    outside_humidity: number;
};

export type GreenhouseClimateUpdate = {
    temperature: number;
    humidity: number;
    outside_temperature?: (number | null);
    outside_humidity?: (number | null);
};

export type GreenhouseCreate = {
    title: string;
    description?: (string | null);
    /**
     * Whether this greenhouse is active
     */
    is_active?: boolean;
    /**
     * Greenhouse style/type
     */
    type?: (string | null);
    /**
     * Current internal temperature
     */
    temperature?: number;
    /**
     * Current internal humidity
     */
    humidity?: number;
    /**
     * Current external temperature
     */
    outside_temperature?: number;
    /**
     * Current external humidity
     */
    outside_humidity?: number;
    /**
     * Latitude of greenhouse location
     */
    latitude?: (number | null);
    /**
     * Longitude of greenhouse location
     */
    longitude?: (number | null);
};

export type GreenhousePublic = {
    title: string;
    description?: (string | null);
    is_active: boolean;
    /**
     * Greenhouse style/type
     */
    type?: (string | null);
    /**
     * Current internal temperature
     */
    temperature?: number;
    /**
     * Current internal humidity
     */
    humidity?: number;
    /**
     * Current external temperature
     */
    outside_temperature?: number;
    /**
     * Current external humidity
     */
    outside_humidity?: number;
    /**
     * Latitude of greenhouse location
     */
    latitude?: (number | null);
    /**
     * Longitude of greenhouse location
     */
    longitude?: (number | null);
    id: string;
    owner_id: string;
};

export type GreenhousesPublic = {
    data: Array<GreenhousePublic>;
    count: number;
};

export type GreenhouseUpdate = {
    title?: (string | null);
    description?: (string | null);
    is_active?: (boolean | null);
    temperature?: (number | null);
    humidity?: (number | null);
    outside_temperature?: (number | null);
    outside_humidity?: (number | null);
    type?: (string | null);
    latitude?: (number | null);
    longitude?: (number | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type LocationEnum = 'N' | 'NE' | 'E' | 'SE' | 'S' | 'SW' | 'W' | 'NW';

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type SensorCreate = {
    /**
     * Sensor name/identifier
     */
    name: string;
    /**
     * Type of sensor
     */
    type: SensorType;
    /**
     * Model/manufacturer information
     */
    model?: (string | null);
    /**
     * Current sensor value
     */
    value?: (number | null);
    /**
     * Unit of measurement
     */
    unit?: (string | null);
    /**
     * Whether this sensor is mapped to a zone
     */
    is_mapped?: boolean;
    controller_id: string;
};

export type SensorPublic = {
    /**
     * Sensor name/identifier
     */
    name: string;
    /**
     * Type of sensor
     */
    type: SensorType;
    /**
     * Model/manufacturer information
     */
    model?: (string | null);
    /**
     * Current sensor value
     */
    value?: (number | null);
    /**
     * Unit of measurement
     */
    unit?: (string | null);
    /**
     * Whether this sensor is mapped to a zone
     */
    is_mapped?: boolean;
    id: string;
    controller_id: string;
};

export type SensorType = 'temperature' | 'humidity' | 'co2' | 'light' | 'soil_moisture';

export type SensorUpdate = {
    name?: (string | null);
    type?: (string | null);
    model?: (string | null);
    value?: (number | null);
    unit?: (string | null);
    controller_id?: (string | null);
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type ZoneCreate = {
    /**
     * Numeric identifier within greenhouse
     */
    zone_number: number;
    /**
     * N, E, S, W, NE, SE, SW, NW
     */
    location: LocationEnum;
    temperature?: (number | null);
    humidity?: (number | null);
    greenhouse_id: string;
};

export type ZoneCropCreate = {
    start_date?: string;
    end_date?: (string | null);
    is_active?: boolean;
    /**
     * Total yield produced
     */
    final_yield?: (number | null);
    /**
     * Area used in square meters
     */
    area_sqm?: (number | null);
    crop_id: string;
    zone_id: string;
};

export type ZoneCropObservationCreate = {
    observed_at?: string;
    notes?: (string | null);
    /**
     * URL to uploaded image
     */
    image_url?: (string | null);
    /**
     * Plant height in cm
     */
    height_cm?: (number | null);
    /**
     * Health score 1-10
     */
    health_score?: (number | null);
    zone_crop_id: string;
};

export type ZoneCropObservationPublic = {
    observed_at?: string;
    notes?: (string | null);
    /**
     * URL to uploaded image
     */
    image_url?: (string | null);
    /**
     * Plant height in cm
     */
    height_cm?: (number | null);
    /**
     * Health score 1-10
     */
    health_score?: (number | null);
    id: string;
    zone_crop_id: string;
};

export type ZoneCropPublic = {
    start_date?: string;
    end_date?: (string | null);
    is_active?: boolean;
    /**
     * Total yield produced
     */
    final_yield?: (number | null);
    /**
     * Area used in square meters
     */
    area_sqm?: (number | null);
    id: string;
    crop_id: string;
    zone_id: string;
};

export type ZoneCropUpdate = {
    crop_id?: (string | null);
    end_date?: (string | null);
    is_active?: (boolean | null);
    final_yield?: (number | null);
    area_sqm?: (number | null);
};

export type ZonePublic = {
    /**
     * Numeric identifier within greenhouse
     */
    zone_number: number;
    /**
     * N, E, S, W, NE, SE, SW, NW
     */
    location: LocationEnum;
    temperature?: (number | null);
    humidity?: (number | null);
    id: string;
    greenhouse_id: string;
};

export type ZoneSensorMap = {
    sensor_id: string;
    type: SensorType;
};

export type ZoneUpdate = {
    zone_number?: (number | null);
    location?: (LocationEnum | null);
};

export type ClimateUpdateClimateData = {
    greenhouseId: string;
    requestBody: GreenhouseClimateUpdate;
};

export type ClimateUpdateClimateResponse = (GreenhousePublic);

export type ClimateReadClimateData = {
    greenhouseId: string;
};

export type ClimateReadClimateResponse = (GreenhouseClimateRead);

export type ControllersCreateControllerData = {
    greenhouseId: string;
    requestBody: ControllerCreate;
};

export type ControllersCreateControllerResponse = (ControllerPublic);

export type ControllersListControllersData = {
    greenhouseId: string;
};

export type ControllersListControllersResponse = (Array<ControllerPublic>);

export type ControllersGetControllerData = {
    controllerId: string;
    greenhouseId: string;
};

export type ControllersGetControllerResponse = (ControllerPublic);

export type ControllersUpdateControllerData = {
    controllerId: string;
    greenhouseId: string;
    requestBody: ControllerUpdate;
};

export type ControllersUpdateControllerResponse = (ControllerPublic);

export type ControllersDeleteControllerData = {
    controllerId: string;
    greenhouseId: string;
};

export type ControllersDeleteControllerResponse = (unknown);

export type CropsListCropsResponse = (Array<CropPublic>);

export type CropsCreateCropData = {
    requestBody: CropCreate;
};

export type CropsCreateCropResponse = (CropPublic);

export type CropsGetCropData = {
    cropId: string;
};

export type CropsGetCropResponse = (CropPublic);

export type CropsUpdateCropData = {
    cropId: string;
    requestBody: CropUpdate;
};

export type CropsUpdateCropResponse = (CropPublic);

export type CropsDeleteCropData = {
    cropId: string;
};

export type CropsDeleteCropResponse = (unknown);

export type CropsGetZoneCropData = {
    zoneId: string;
};

export type CropsGetZoneCropResponse = (ZoneCropPublic);

export type CropsPlantCropInZoneData = {
    requestBody: ZoneCropCreate;
    zoneId: string;
};

export type CropsPlantCropInZoneResponse = (ZoneCropPublic);

export type CropsUpdateZoneCropData = {
    requestBody: ZoneCropUpdate;
    zoneId: string;
};

export type CropsUpdateZoneCropResponse = (ZoneCropPublic);

export type CropsHarvestCropFromZoneData = {
    zoneId: string;
};

export type CropsHarvestCropFromZoneResponse = (unknown);

export type CropsListZoneCropHistoryData = {
    zoneId: string;
};

export type CropsListZoneCropHistoryResponse = (Array<ZoneCropPublic>);

export type CropsPermanentlyDeleteZoneCropData = {
    zoneCropId: string;
    zoneId: string;
};

export type CropsPermanentlyDeleteZoneCropResponse = (unknown);

export type CropsGetZoneCropAnalyticsData = {
    zoneId: string;
};

export type CropsGetZoneCropAnalyticsResponse = (unknown);

export type CropsListZoneCropObservationsData = {
    zoneId: string;
};

export type CropsListZoneCropObservationsResponse = (Array<ZoneCropObservationPublic>);

export type CropsCreateZoneCropObservationData = {
    requestBody: ZoneCropObservationCreate;
    zoneId: string;
};

export type CropsCreateZoneCropObservationResponse = (ZoneCropObservationPublic);

export type CreateUserCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type CreateUserCreateUserResponse = (UserPublic);

export type GreenhousesReadGreenhousesData = {
    limit?: number;
    skip?: number;
};

export type GreenhousesReadGreenhousesResponse = (GreenhousesPublic);

export type GreenhousesCreateGreenhouseData = {
    requestBody: GreenhouseCreate;
};

export type GreenhousesCreateGreenhouseResponse = (GreenhousePublic);

export type GreenhousesReadGreenhouseData = {
    greenhouseId: string;
};

export type GreenhousesReadGreenhouseResponse = (GreenhousePublic);

export type GreenhousesUpdateGreenhouseData = {
    greenhouseId: string;
    requestBody: GreenhouseUpdate;
};

export type GreenhousesUpdateGreenhouseResponse = (GreenhousePublic);

export type GreenhousesDeleteGreenhouseData = {
    greenhouseId: string;
};

export type GreenhousesDeleteGreenhouseResponse = (Message);

export type GreenhousesListGreenhouseSensorsData = {
    greenhouseId: string;
};

export type GreenhousesListGreenhouseSensorsResponse = (Array<SensorPublic>);

export type GreenhousesListUnmappedGreenhouseSensorsData = {
    greenhouseId: string;
};

export type GreenhousesListUnmappedGreenhouseSensorsResponse = (Array<SensorPublic>);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type SensorsCreateSensorData = {
    controllerId: string;
    requestBody: SensorCreate;
};

export type SensorsCreateSensorResponse = (SensorPublic);

export type SensorsListSensorsData = {
    controllerId: string;
};

export type SensorsListSensorsResponse = (Array<SensorPublic>);

export type SensorsGetSensorData = {
    sensorId: string;
};

export type SensorsGetSensorResponse = (SensorPublic);

export type SensorsUpdateSensorData = {
    requestBody: SensorUpdate;
    sensorId: string;
};

export type SensorsUpdateSensorResponse = (SensorPublic);

export type SensorsDeleteSensorData = {
    sensorId: string;
};

export type SensorsDeleteSensorResponse = (unknown);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);

export type ZonesCreateZoneData = {
    greenhouseId: string;
    requestBody: ZoneCreate;
};

export type ZonesCreateZoneResponse = (ZonePublic);

export type ZonesListZonesData = {
    greenhouseId: string;
};

export type ZonesListZonesResponse = (Array<ZonePublic>);

export type ZonesGetZoneData = {
    greenhouseId: string;
    zoneId: string;
};

export type ZonesGetZoneResponse = (ZonePublic);

export type ZonesUpdateZoneData = {
    greenhouseId: string;
    requestBody: ZoneUpdate;
    zoneId: string;
};

export type ZonesUpdateZoneResponse = (ZonePublic);

export type ZonesDeleteZoneData = {
    greenhouseId: string;
    zoneId: string;
};

export type ZonesDeleteZoneResponse = (Message);

export type ZonesListZoneSensorsData = {
    zoneId: string;
};

export type ZonesListZoneSensorsResponse = (Array<SensorPublic>);

export type ZonesMapSensorToZoneEndpointData = {
    requestBody: ZoneSensorMap;
    zoneId: string;
};

export type ZonesMapSensorToZoneEndpointResponse = (ZonePublic);

export type ZonesUnmapSensorFromZoneEndpointData = {
    sensorType: SensorType;
    zoneId: string;
};

export type ZonesUnmapSensorFromZoneEndpointResponse = (ZonePublic);