// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type ControllerCreate = {
    /**
     * Controller name, e.g. 'fan', 'heater'
     */
    name: string;
    model?: (string | null);
    greenhouse_id: string;
};

export type ControllerPublic = {
    /**
     * Controller name, e.g. 'fan', 'heater'
     */
    name: string;
    model?: (string | null);
    id: string;
    greenhouse_id: string;
};

export type ControllerUpdate = {
    name?: (string | null);
    model?: (string | null);
};

export type GreenhouseClimateRead = {
    temperature: number;
    humidity: number;
    outside_temperature: number;
    outside_humidity: number;
};

export type GreenhouseClimateUpdate = {
    temperature: number;
    humidity: number;
    outside_temperature?: (number | null);
    outside_humidity?: (number | null);
};

export type GreenhouseCreate = {
    title: string;
    description?: (string | null);
    /**
     * Whether this greenhouse is active
     */
    is_active?: boolean;
    /**
     * Current internal temperature
     */
    temperature?: number;
    /**
     * Current internal humidity
     */
    humidity?: number;
    /**
     * Current external temperature
     */
    outside_temperature?: number;
    /**
     * Current external humidity
     */
    outside_humidity?: number;
    /**
     * Greenhouse style/type
     */
    type?: (string | null);
    /**
     * Latitude of greenhouse location
     */
    latitude?: (number | null);
    /**
     * Longitude of greenhouse location
     */
    longitude?: (number | null);
};

export type GreenhousePublic = {
    title: string;
    description?: (string | null);
    is_active: boolean;
    /**
     * Current internal temperature
     */
    temperature?: number;
    /**
     * Current internal humidity
     */
    humidity?: number;
    /**
     * Current external temperature
     */
    outside_temperature?: number;
    /**
     * Current external humidity
     */
    outside_humidity?: number;
    /**
     * Greenhouse style/type
     */
    type?: (string | null);
    /**
     * Latitude of greenhouse location
     */
    latitude?: (number | null);
    /**
     * Longitude of greenhouse location
     */
    longitude?: (number | null);
    id: string;
    owner_id: string;
};

export type GreenhousesPublic = {
    data: Array<GreenhousePublic>;
    count: number;
};

export type GreenhouseUpdate = {
    title?: (string | null);
    description?: (string | null);
    is_active?: (boolean | null);
    temperature?: (number | null);
    humidity?: (number | null);
    outside_temperature?: (number | null);
    outside_humidity?: (number | null);
    type?: (string | null);
    latitude?: (number | null);
    longitude?: (number | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type LocationEnum = 'N' | 'NE' | 'E' | 'SE' | 'S' | 'SW' | 'W' | 'NW';

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type SensorCreate = {
    /**
     * Sensor name/identifier
     */
    name: string;
    /**
     * Type of sensor (temperature, humidity, etc.)
     */
    type: string;
    /**
     * Model/manufacturer information
     */
    model?: (string | null);
    /**
     * Current sensor value
     */
    value?: (number | null);
    /**
     * Unit of measurement
     */
    unit?: (string | null);
    zone_id: string;
    controller_id?: (string | null);
};

export type SensorPublic = {
    /**
     * Sensor name/identifier
     */
    name: string;
    /**
     * Type of sensor (temperature, humidity, etc.)
     */
    type: string;
    /**
     * Model/manufacturer information
     */
    model?: (string | null);
    /**
     * Current sensor value
     */
    value?: (number | null);
    /**
     * Unit of measurement
     */
    unit?: (string | null);
    id: string;
    zone_id: string;
};

export type SensorUpdate = {
    name?: (string | null);
    type?: (string | null);
    model?: (string | null);
    value?: (number | null);
    unit?: (string | null);
    controller_id?: (string | null);
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type ZoneCreate = {
    /**
     * Numeric identifier within greenhouse
     */
    zone_number: number;
    /**
     * N, E, S, W, NE, SE, SW, NW
     */
    location: LocationEnum;
    temperature?: (number | null);
    humidity?: (number | null);
    greenhouse_id: string;
};

export type ZonePublic = {
    /**
     * Numeric identifier within greenhouse
     */
    zone_number: number;
    /**
     * N, E, S, W, NE, SE, SW, NW
     */
    location: LocationEnum;
    temperature?: (number | null);
    humidity?: (number | null);
    id: string;
    greenhouse_id: string;
};

export type ZoneReading = {
    id?: string;
    zone_id: string;
    timestamp?: string;
    temperature: number;
    humidity: number;
};

export type ZoneUpdate = {
    zone_number?: (number | null);
    location?: (LocationEnum | null);
};

export type GreenhouseUpdateClimateData = {
    greenhouseId: string;
    requestBody: GreenhouseClimateUpdate;
};

export type GreenhouseUpdateClimateResponse = (GreenhousePublic);

export type GreenhouseReadClimateData = {
    greenhouseId: string;
};

export type GreenhouseReadClimateResponse = (GreenhouseClimateRead);

export type GreenhouseListControllersResponse = (Array<ControllerPublic>);

export type GreenhouseCreateControllerData = {
    requestBody: ControllerCreate;
};

export type GreenhouseCreateControllerResponse = (ControllerPublic);

export type GreenhouseGetControllerData = {
    controllerId: string;
};

export type GreenhouseGetControllerResponse = (ControllerPublic);

export type GreenhouseUpdateControllerData = {
    controllerId: string;
    requestBody: ControllerUpdate;
};

export type GreenhouseUpdateControllerResponse = (ControllerPublic);

export type GreenhouseDeleteControllerData = {
    controllerId: string;
};

export type GreenhouseDeleteControllerResponse = (unknown);

export type CreateUserCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type CreateUserCreateUserResponse = (UserPublic);

export type GreenhouseListZonesResponse = (Array<ZonePublic>);

export type GreenhouseCreateZoneData = {
    requestBody: ZoneCreate;
};

export type GreenhouseCreateZoneResponse = (ZonePublic);

export type GreenhouseGetZoneData = {
    zoneId: string;
};

export type GreenhouseGetZoneResponse = (ZonePublic);

export type GreenhouseUpdateZoneData = {
    requestBody: ZoneUpdate;
    zoneId: string;
};

export type GreenhouseUpdateZoneResponse = (ZonePublic);

export type GreenhouseDeleteZoneData = {
    zoneId: string;
};

export type GreenhouseDeleteZoneResponse = (Message);

export type GreenhouseUpdateZoneReadingsData = {
    zoneId: string;
};

export type GreenhouseUpdateZoneReadingsResponse = (ZoneReading);

export type GreenhouseGetZoneReadingData = {
    zoneId: string;
};

export type GreenhouseGetZoneReadingResponse = (ZoneReading);

export type GreenhouseGetZoneReadingsData = {
    zoneId: string;
};

export type GreenhouseGetZoneReadingsResponse = (Array<ZoneReading>);

export type GreenhouseCreateSensorData = {
    requestBody: SensorCreate;
};

export type GreenhouseCreateSensorResponse = (SensorPublic);

export type GreenhouseListSensorsData = {
    zoneId: string;
};

export type GreenhouseListSensorsResponse = (Array<SensorPublic>);

export type GreenhouseGetSensorData = {
    sensorId: string;
};

export type GreenhouseGetSensorResponse = (SensorPublic);

export type GreenhouseUpdateSensorData = {
    requestBody: SensorUpdate;
    sensorId: string;
};

export type GreenhouseUpdateSensorResponse = (SensorPublic);

export type GreenhouseDeleteSensorData = {
    sensorId: string;
};

export type GreenhouseDeleteSensorResponse = (unknown);

export type GreenhousesReadGreenhousesData = {
    limit?: number;
    skip?: number;
};

export type GreenhousesReadGreenhousesResponse = (GreenhousesPublic);

export type GreenhousesCreateGreenhouseData = {
    requestBody: GreenhouseCreate;
};

export type GreenhousesCreateGreenhouseResponse = (GreenhousePublic);

export type GreenhousesReadGreenhouseData = {
    greenhouseId: string;
};

export type GreenhousesReadGreenhouseResponse = (GreenhousePublic);

export type GreenhousesUpdateGreenhouseData = {
    greenhouseId: string;
    requestBody: GreenhouseUpdate;
};

export type GreenhousesUpdateGreenhouseResponse = (GreenhousePublic);

export type GreenhousesDeleteGreenhouseData = {
    greenhouseId: string;
};

export type GreenhousesDeleteGreenhouseResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);