// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type EquipmentCreate = {
    /**
     * Equipment name, e.g. 'fan', 'heater'
     */
    name: string;
    model?: (string | null);
    greenhouse_id: string;
};

export type EquipmentPublic = {
    /**
     * Equipment name, e.g. 'fan', 'heater'
     */
    name: string;
    model?: (string | null);
    id: string;
    greenhouse_id: string;
};

export type EquipmentUpdate = {
    name?: (string | null);
    model?: (string | null);
};

export type GreenhouseClimateUpdate = {
    temperature: number;
    humidity: number;
    outside_temperature?: (number | null);
    outside_humidity?: (number | null);
};

export type GreenhouseCreate = {
    title: string;
    description?: (string | null);
    /**
     * Whether this greenhouse is active
     */
    is_active?: boolean;
    /**
     * Current internal temperature
     */
    temperature?: number;
    /**
     * Current internal humidity
     */
    humidity?: number;
    /**
     * Current external temperature
     */
    outside_temperature?: number;
    /**
     * Current external humidity
     */
    outside_humidity?: number;
    /**
     * Greenhouse style/type
     */
    type?: (string | null);
    /**
     * Latitude of greenhouse location
     */
    latitude?: (number | null);
    /**
     * Longitude of greenhouse location
     */
    longitude?: (number | null);
};

export type GreenhousePublic = {
    title: string;
    description?: (string | null);
    is_active: boolean;
    /**
     * Current internal temperature
     */
    temperature?: number;
    /**
     * Current internal humidity
     */
    humidity?: number;
    /**
     * Current external temperature
     */
    outside_temperature?: number;
    /**
     * Current external humidity
     */
    outside_humidity?: number;
    /**
     * Greenhouse style/type
     */
    type?: (string | null);
    /**
     * Latitude of greenhouse location
     */
    latitude?: (number | null);
    /**
     * Longitude of greenhouse location
     */
    longitude?: (number | null);
    id: string;
    owner_id: string;
};

export type GreenhousesPublic = {
    data: Array<GreenhousePublic>;
    count: number;
};

export type GreenhouseUpdate = {
    title?: (string | null);
    description?: (string | null);
    is_active?: (boolean | null);
    temperature?: (number | null);
    humidity?: (number | null);
    outside_temperature?: (number | null);
    outside_humidity?: (number | null);
    type?: (string | null);
    latitude?: (number | null);
    longitude?: (number | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type LocationEnum = 'N' | 'NE' | 'E' | 'SE' | 'S' | 'SW' | 'W' | 'NW';

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type SensorPayload = {
    sensor_type: string;
    value: number;
    timestamp: string;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type ZoneCreate = {
    /**
     * Numeric identifier within greenhouse
     */
    zone_number: number;
    /**
     * N, E, S, W, NE, SE, SW, NW
     */
    location: LocationEnum;
    greenhouse_id: string;
};

export type ZonePublic = {
    /**
     * Numeric identifier within greenhouse
     */
    zone_number: number;
    /**
     * N, E, S, W, NE, SE, SW, NW
     */
    location: LocationEnum;
    id: string;
    greenhouse_id: string;
};

export type ZoneUpdate = {
    zone_number?: (number | null);
    location?: (LocationEnum | null);
};

export type EquipmentListEquipmentResponse = (Array<EquipmentPublic>);

export type EquipmentCreateEquipmentData = {
    requestBody: EquipmentCreate;
};

export type EquipmentCreateEquipmentResponse = (EquipmentPublic);

export type EquipmentGetEquipmentData = {
    equipmentId: string;
};

export type EquipmentGetEquipmentResponse = (EquipmentPublic);

export type EquipmentUpdateEquipmentData = {
    equipmentId: string;
    requestBody: EquipmentUpdate;
};

export type EquipmentUpdateEquipmentResponse = (EquipmentPublic);

export type EquipmentDeleteEquipmentData = {
    equipmentId: string;
};

export type EquipmentDeleteEquipmentResponse = (unknown);

export type GreenhousesReadGreenhousesData = {
    limit?: number;
    skip?: number;
};

export type GreenhousesReadGreenhousesResponse = (GreenhousesPublic);

export type GreenhousesCreateGreenhouseData = {
    requestBody: GreenhouseCreate;
};

export type GreenhousesCreateGreenhouseResponse = (GreenhousePublic);

export type GreenhousesReadGreenhouseData = {
    greenhouseId: string;
};

export type GreenhousesReadGreenhouseResponse = (GreenhousePublic);

export type GreenhousesUpdateGreenhouseData = {
    greenhouseId: string;
    requestBody: GreenhouseUpdate;
};

export type GreenhousesUpdateGreenhouseResponse = (GreenhousePublic);

export type GreenhousesDeleteGreenhouseData = {
    greenhouseId: string;
};

export type GreenhousesDeleteGreenhouseResponse = (Message);

export type GreenhousesAddSensorDataData = {
    greenhouseId: string;
    requestBody: SensorPayload;
};

export type GreenhousesAddSensorDataResponse = (GreenhousePublic);

export type GreenhousesUpdateClimateData = {
    greenhouseId: string;
    requestBody: GreenhouseClimateUpdate;
};

export type GreenhousesUpdateClimateResponse = (GreenhousePublic);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);

export type ZonesListZonesResponse = (Array<ZonePublic>);

export type ZonesCreateZoneData = {
    requestBody: ZoneCreate;
};

export type ZonesCreateZoneResponse = (ZonePublic);

export type ZonesGetZoneData = {
    zoneId: string;
};

export type ZonesGetZoneResponse = (ZonePublic);

export type ZonesUpdateZoneData = {
    requestBody: ZoneUpdate;
    zoneId: string;
};

export type ZonesUpdateZoneResponse = (ZonePublic);

export type ZonesDeleteZoneData = {
    zoneId: string;
};

export type ZonesDeleteZoneResponse = (Message);