global:
  checkNewVersion: false
  sendAnonymousUsage: false

api:
  dashboard: true
  insecure: false

ping: {}

log:
  level: INFO

entryPoints:
  websecure:
    address: ":443"

providers:
  docker:
    exposedByDefault: false
    network: verdify-proxy
  file:
    directory: /etc/traefik/dynamic
    watch: true
