"""
GreenLight/scripts/sensitivity.py

One-at-a-time (OAT) parameter sensitivity analysis for the Longmont greenhouse.

Runs the GreenLight sim across three representative seasons (Jan, Apr, Jul),
varying each of the three calibration parameters across its range while holding
the other two at their defaults.

Why do this before real data arrives?
    When calibrate.py reports "sim runs 5 °F cold in April," you'll already
    know which lever fixes it, by how much, and whether the fix is the same
    in winter vs summer.  This also surfaces which parameters are
    over-/under-powered so the Nelder-Mead search doesn't waste time on
    insensitive dimensions.

Usage:
    python scripts/sensitivity.py
    python scripts/sensitivity.py --workers 4   # parallel, default: CPU-2

Output:
    Console table + calibration/sensitivity_report.json
"""

import argparse
import json
import os
import sys
import warnings
from multiprocessing import Pool

import numpy as np
import pandas as pd

project_dir = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
sys.path.insert(0, project_dir)
import greenlight  # noqa: E402

BASE_PATH   = os.path.join(project_dir, "greenlight", "models")
MODEL       = os.path.join("katzin_2021", "definition", "main_longmont.json")
TEMP_SUBDIR = os.path.join("katzin_2021", "output", "_sens_temp")
CALIB_DIR   = os.path.join(project_dir, "calibration")

# Boulder TMYx weather (generated by prepare_longmont_weather.py)
WEATHER_FILE = os.path.join(
    BASE_PATH, "katzin_2021", "input_data", "longmont",
    "longmont_weather_from_jan_01_000000.csv",
)

WINDOW_DAYS = 7   # days per simulation run

# ── Seasons ───────────────────────────────────────────────────────────────────
# (label, start_day_of_year)  — chosen to avoid shoulder transitions
SEASONS = [
    ("Jan_winter",  10),   # deep winter — max heating load
    ("Apr_spring",  95),   # spring — moderate heating, first solar gain
    ("Jul_summer",  185),  # summer — max cooling/ventilation load
]

# ── Calibration parameter space ───────────────────────────────────────────────
# (default, lo, hi, n_steps)
CAL_PARAMS = {
    "cLeakage":  (3e-4,  1e-4,  1.5e-3, 7),
    "aCov":      (74.8,  55.0,  78.0,   7),
    "lambdaRf":  (0.021, 0.010, 0.060,  7),
}


# ── Simulation helpers ────────────────────────────────────────────────────────

def _load_output(path: str) -> pd.DataFrame:
    raw  = pd.read_csv(path, header=None, low_memory=False)
    cols = raw.iloc[0]
    data = raw.iloc[3:].reset_index(drop=True).apply(pd.to_numeric, errors="coerce")
    data.columns = cols
    return data


def _aggregate(data: pd.DataFrame, season_label: str, param_name: str,
               param_val: float) -> dict:
    dt_s = float(data["Time"].iloc[1]) - float(data["Time"].iloc[0])

    tair_c    = data["tAir"].dropna()
    tair_f    = tair_c * 9 / 5 + 32

    rh        = data["rhIn"].dropna() if "rhIn" in data.columns else pd.Series(dtype=float)
    ublow     = data["uBlow"] if "uBlow" in data.columns else pd.Series(dtype=float)
    uventf    = data["uVentForced"] if "uVentForced" in data.columns else pd.Series(dtype=float)
    hblow     = data["hBlowAir"] if "hBlowAir" in data.columns else pd.Series(0.0, index=data.index)

    heat_mj   = float(dt_s * hblow.fillna(0).sum() * 1e-6)

    return {
        "season":       season_label,
        "param":        param_name,
        "value":        float(param_val),
        "mean_tAir_f":  round(float(tair_f.mean()), 2),
        "min_tAir_f":   round(float(tair_f.min()), 2),
        "max_tAir_f":   round(float(tair_f.max()), 2),
        "mean_rh_pct":  round(float(rh.mean()), 1) if len(rh) else float("nan"),
        "heat_frac":    round(float((ublow > 0.1).mean()), 3),
        "fan_frac":     round(float((uventf > 0.1).mean()), 3),
        "heat_mj_m2":   round(heat_mj, 2),
    }


def _run_one(args: tuple) -> dict | None:
    """Worker: run one simulation and return aggregated metrics."""
    (sim_id, season_label, start_day, param_name, param_val,
     other_params, weather_file) = args

    out_rel = os.path.join(TEMP_SUBDIR, f"sens_{sim_id:04d}.csv")
    out_abs = os.path.join(BASE_PATH, out_rel)
    os.makedirs(os.path.dirname(out_abs), exist_ok=True)

    t_start_s = start_day * 86400
    t_end_s   = t_start_s + WINDOW_DAYS * 86400
    options   = {"options": {"t_start": str(t_start_s), "t_end": str(t_end_s)}}

    # Build override list: the swept param + the other two at their defaults
    all_params = {**other_params, param_name: param_val}
    overrides  = [{k: {"definition": f"{v:.8g}"}} for k, v in all_params.items()]

    input_prompt = [MODEL, options] + overrides + [weather_file]

    try:
        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            mdl = greenlight.GreenLight(
                base_path=BASE_PATH,
                input_prompt=input_prompt,
                output_path=out_rel,
            )
            mdl.run()

        data   = _load_output(out_abs)
        result = _aggregate(data, season_label, param_name, param_val)
        return result

    except Exception as exc:
        print(f"  [sim {sim_id}] FAILED ({season_label}, {param_name}={param_val:.4g}): {exc}")
        return None

    finally:
        for path in [out_abs,
                     out_abs.replace(".csv", "_model_struct_log.json"),
                     out_abs.replace(".csv", "_simulation_log.txt")]:
            if os.path.exists(path):
                os.remove(path)


# ── Reporting ─────────────────────────────────────────────────────────────────

def _sensitivity_stats(rows: list[dict], param_name: str) -> dict:
    """
    For a given parameter, compute Δ(mean_tAir_f) per unit change
    across all seasons.  This is the key number: "how many °F does
    a 1-unit increase in this parameter buy you?"
    """
    subset = [r for r in rows if r["param"] == param_name and r is not None]
    stats  = {}
    for season in [s[0] for s in SEASONS]:
        s_rows  = sorted([r for r in subset if r["season"] == season],
                         key=lambda r: r["value"])
        if len(s_rows) < 2:
            continue
        vals    = np.array([r["value"]        for r in s_rows])
        tairs   = np.array([r["mean_tAir_f"]  for r in s_rows])
        heats   = np.array([r["heat_frac"]    for r in s_rows])
        # Sensitivity = total swing / total parameter range
        t_swing   = tairs[-1] - tairs[0]
        h_swing   = heats[-1] - heats[0]
        p_range   = vals[-1]  - vals[0]
        stats[season] = {
            "tAir_swing_f":   round(t_swing, 2),
            "heat_swing_pct": round(h_swing * 100, 1),
            "param_range":    (float(vals[0]), float(vals[-1])),
        }
    return stats


def _print_table(rows: list[dict], param_name: str) -> None:
    subset = [r for r in rows if r["param"] == param_name and r is not None]
    if not subset:
        return

    values = sorted(set(r["value"] for r in subset))
    seasons = [s[0] for s in SEASONS]

    print(f"\n  {'Value':>12}", end="")
    for s in seasons:
        print(f"  {s[:11]:>11}  heat%  fan%", end="")
    print()
    print("  " + "-" * (12 + len(seasons) * 26))

    for v in values:
        # mark the default
        default_v = CAL_PARAMS[param_name][0]
        marker = " ←" if abs(v - default_v) / max(abs(default_v), 1e-10) < 0.02 else "  "
        print(f"  {v:>12.5g}{marker}", end="")
        for s in seasons:
            r_list = [r for r in subset if r["season"] == s and abs(r["value"] - v) < 1e-9 * max(abs(v), 1)]
            if r_list:
                r = r_list[0]
                print(f"  {r['mean_tAir_f']:>7.1f}°F  {r['heat_frac']*100:>5.1f}%"
                      f"  {r['fan_frac']*100:>4.1f}%", end="")
            else:
                print(f"  {'---':>7}    ---    ---", end="")
        print()


# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    ap = argparse.ArgumentParser(description="OAT parameter sensitivity for GreenLight")
    ap.add_argument("--workers", type=int,
                    default=max(1, (os.cpu_count() or 4) - 2),
                    help="Parallel workers (default: CPU count − 2)")
    args = ap.parse_args()

    if not os.path.exists(WEATHER_FILE):
        print(f"ERROR: Boulder TMYx weather file not found:\n  {WEATHER_FILE}")
        print("Run:  python scripts/prepare_longmont_weather.py  first.")
        sys.exit(1)

    # ── Build job list ────────────────────────────────────────────────────────
    jobs  = []
    sim_id = 0
    defaults = {n: CAL_PARAMS[n][0] for n in CAL_PARAMS}

    for param_name, (default, lo, hi, n_steps) in CAL_PARAMS.items():
        # Use log spacing for cLeakage (spans a decade), linear for others
        if param_name == "cLeakage":
            values = np.logspace(np.log10(lo), np.log10(hi), n_steps)
        else:
            values = np.linspace(lo, hi, n_steps)

        # Ensure the default is always included
        if not any(abs(v - default) / max(abs(default), 1e-10) < 0.01 for v in values):
            values = np.sort(np.append(values, default))

        for season_label, start_day in SEASONS:
            other = {k: v for k, v in defaults.items() if k != param_name}
            for val in values:
                jobs.append((
                    sim_id, season_label, start_day,
                    param_name, float(val), other, WEATHER_FILE,
                ))
                sim_id += 1

    total = len(jobs)
    print(f"\n{'='*60}")
    print(f"  GreenLight parameter sensitivity analysis")
    print(f"  {len(CAL_PARAMS)} params × {n_steps}+ values × {len(SEASONS)} seasons "
          f"= {total} simulations")
    print(f"  Workers : {args.workers}  |  {WINDOW_DAYS}-day windows")
    print(f"{'='*60}\n")

    # ── Run simulations ───────────────────────────────────────────────────────
    results   = []
    completed = 0

    with Pool(processes=args.workers) as pool:
        for result in pool.imap_unordered(_run_one, jobs):
            completed += 1
            if result is not None:
                results.append(result)
                print(f"  [{completed:>3}/{total}]  {result['season']:12s}"
                      f"  {result['param']:12s}={result['value']:.4g}"
                      f"  tAir={result['mean_tAir_f']:.1f}°F"
                      f"  heat={result['heat_frac']*100:.0f}%"
                      f"  fan={result['fan_frac']*100:.0f}%")
            else:
                print(f"  [{completed:>3}/{total}]  (skipped)")

    # ── Report ────────────────────────────────────────────────────────────────
    print(f"\n\n{'='*60}")
    print(f"  SENSITIVITY RESULTS  (higher swing = stronger lever)")
    print(f"{'='*60}")

    summary = {}
    for param_name in CAL_PARAMS:
        print(f"\n── {param_name}  "
              f"[range: {CAL_PARAMS[param_name][1]:.4g} → {CAL_PARAMS[param_name][2]:.4g},"
              f"  default: {CAL_PARAMS[param_name][0]:.4g}] ──")
        _print_table(results, param_name)

        stats = _sensitivity_stats(results, param_name)
        summary[param_name] = stats
        print(f"\n  Swing summary (across full range):")
        for season, s in stats.items():
            arrow = "↑" if s["tAir_swing_f"] > 0 else "↓"
            print(f"    {season:14s}  tAir {arrow}{abs(s['tAir_swing_f']):.1f}°F"
                  f"  heat {s['heat_swing_pct']:+.1f}pp")

    # ── Interpretation guide ──────────────────────────────────────────────────
    print(f"\n\n── How to read these results ───────────────────────────────────")
    print("  When calibrate.py reports a baseline bias, use this table to")
    print("  pick the right lever:")
    print()
    for param_name in CAL_PARAMS:
        stats  = summary[param_name]
        swings = [abs(s["tAir_swing_f"]) for s in stats.values()]
        if not swings:
            continue
        mean_swing = np.mean(swings)
        direction  = "increasing raises tAir" if list(stats.values())[0]["tAir_swing_f"] > 0 else "increasing lowers tAir"
        print(f"  {param_name:20s}  avg swing {mean_swing:.1f}°F  ({direction})")

    # ── Save JSON ─────────────────────────────────────────────────────────────
    os.makedirs(CALIB_DIR, exist_ok=True)
    out_path = os.path.join(CALIB_DIR, "sensitivity_report.json")
    report   = {
        "window_days":   WINDOW_DAYS,
        "seasons":       [s[0] for s in SEASONS],
        "params":        {k: {"default": v[0], "lo": v[1], "hi": v[2]}
                          for k, v in CAL_PARAMS.items()},
        "sensitivity":   summary,
        "rows":          results,
    }
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(report, f, indent=2)
    print(f"\nFull report saved to: {out_path}")
    print(f"({len(results)}/{total} simulations succeeded)\n")


if __name__ == "__main__":
    main()
