"""verdify_schemas — shared Pydantic contracts.

The database is the source of truth; every other layer (MCP tools, ingestor
tasks, ESP32 readback, vault writers, website renderer) validates through
these schemas so malformed data fails at the boundary instead of
partial-writing.
"""

from .alerts import (
    AlertAckPayload,
    AlertAction,
    AlertCategory,
    AlertDisposition,
    AlertEnvelope,
    AlertLogRow,
    AlertResolvePayload,
    AlertSeverity,
)
from .crops import (
    Crop,
    CropAction,
    CropCreate,
    CropEvent,
    CropEventType,
    CropStage,
    CropUpdate,
    EventCreate,
    Observation,
    ObservationAction,
    ObservationCreate,
    ObservationType,
)
from .daily import DailySummaryRow
from .external import (
    HAEntityState,
    OpenMeteoForecastResponse,
    OpenMeteoHourly,
)
from .forecast import ForecastHour
from .lessons import (
    LessonAction,
    LessonConfidence,
    LessonCreate,
    LessonUpdate,
    LessonValidate,
    PlannerLesson,
)
from .plan import (
    Conditions,
    ParamRationale,
    Plan,
    PlanEvaluation,
    PlanHypothesisStructured,
    PlanId,
    PlanJournalRow,
    PlanSource,
    PlanTransition,
    StressWindow,
)
from .setpoint import (
    SetpointChange,
    SetpointClamp,
    SetpointPlanRow,
    SetpointSnapshot,
    SetpointSource,
)
from .telemetry import (
    ClimateRow,
    Diagnostics,
    EnergySample,
    EquipmentStateEvent,
    OverrideEvent,
    SystemStateRow,
)
from .tunables import ALL_TUNABLES, NUMERIC_TUNABLES, SWITCH_TUNABLES, TunableParameter
from .vault import (
    CropVaultFrontmatter,
    DailyPlanVaultFrontmatter,
    DailyVaultFrontmatter,
    ForecastVaultFrontmatter,
    LessonsVaultFrontmatter,
    VaultFrontmatter,
)
from .views import (
    ClampActivity24h,
    DailyOscillation,
    DailyOscillationSummary,
    DewPointRiskRow,
    OverrideActivity24h,
    PlanAccuracy,
    PlannerPerformance,
    WaterBudgetRow,
)

__all__ = [
    "ALL_TUNABLES",
    "AlertAckPayload",
    "AlertAction",
    "AlertCategory",
    "AlertDisposition",
    "AlertEnvelope",
    "AlertLogRow",
    "AlertResolvePayload",
    "AlertSeverity",
    "ClampActivity24h",
    "ClimateRow",
    "Conditions",
    "DailyOscillation",
    "DailyOscillationSummary",
    "DewPointRiskRow",
    "Crop",
    "CropAction",
    "CropCreate",
    "CropEvent",
    "CropEventType",
    "CropStage",
    "CropUpdate",
    "CropVaultFrontmatter",
    "DailyPlanVaultFrontmatter",
    "DailySummaryRow",
    "DailyVaultFrontmatter",
    "Diagnostics",
    "EnergySample",
    "EquipmentStateEvent",
    "EventCreate",
    "ForecastHour",
    "ForecastVaultFrontmatter",
    "HAEntityState",
    "LessonAction",
    "LessonConfidence",
    "LessonCreate",
    "LessonUpdate",
    "LessonValidate",
    "LessonsVaultFrontmatter",
    "NUMERIC_TUNABLES",
    "Observation",
    "ObservationAction",
    "ObservationCreate",
    "ObservationType",
    "OpenMeteoForecastResponse",
    "OpenMeteoHourly",
    "OverrideActivity24h",
    "OverrideEvent",
    "ParamRationale",
    "Plan",
    "PlanAccuracy",
    "PlanEvaluation",
    "PlanHypothesisStructured",
    "PlanId",
    "PlanJournalRow",
    "PlanSource",
    "PlanTransition",
    "PlannerLesson",
    "PlannerPerformance",
    "SWITCH_TUNABLES",
    "SetpointChange",
    "SetpointClamp",
    "SetpointPlanRow",
    "SetpointSnapshot",
    "SetpointSource",
    "StressWindow",
    "SystemStateRow",
    "TunableParameter",
    "VaultFrontmatter",
    "WaterBudgetRow",
]
