"""verdify_schemas — shared Pydantic contracts.

The database is the source of truth; every other layer (MCP tools, ingestor
tasks, ESP32 readback, vault writers, website renderer) validates through
these schemas so malformed data fails at the boundary instead of
partial-writing.
"""

from .alerts import (
    AlertAckPayload,
    AlertAction,
    AlertCategory,
    AlertDisposition,
    AlertEnvelope,
    AlertLogRow,
    AlertResolvePayload,
    AlertSeverity,
)
from .api import (
    APIStatus,
    CropDetail,
    CropHealthSummaryItem,
    CropListItem,
    CropRecentObservation,
    HealthTrendPoint,
    ObservationWithCrop,
    ZoneDetail,
    ZoneListItem,
    ZoneObservation,
)
from .crop_profiles import CropTargetProfile
from .crops import (
    Crop,
    CropAction,
    CropCreate,
    CropEvent,
    CropEventType,
    CropStage,
    CropUpdate,
    EventCreate,
    Observation,
    ObservationAction,
    ObservationCreate,
    ObservationType,
)
from .daily import DailySummaryRow
from .external import (
    HAEntityState,
    OpenMeteoForecastResponse,
    OpenMeteoHourly,
)
from .forecast import ForecastHour
from .forecast_ops import ForecastActionLog, ForecastActionRule, ForecastActionType
from .lessons import (
    LessonAction,
    LessonConfidence,
    LessonCreate,
    LessonUpdate,
    LessonValidate,
    PlannerLesson,
)
from .media import ImageObservation
from .operations import (
    ConsumablesLog,
    Harvest,
    IrrigationLog,
    IrrigationSchedule,
    LabResult,
    MaintenanceLog,
    Treatment,
)
from .plan import (
    Conditions,
    ParamRationale,
    Plan,
    PlanEvaluation,
    PlanHypothesisStructured,
    PlanId,
    PlanJournalRow,
    PlanSource,
    PlanTransition,
    StressWindow,
)
from .setpoint import (
    SetpointChange,
    SetpointClamp,
    SetpointPlanRow,
    SetpointSnapshot,
    SetpointSource,
)
from .system_infra import (
    DataGap,
    DataGapStatus,
    ESP32LogLevel,
    ESP32LogRow,
    SensorRegistry,
    UtilityCategory,
    UtilityCost,
)
from .telemetry import (
    ClimateRow,
    Diagnostics,
    EnergySample,
    EquipmentStateEvent,
    OverrideEvent,
    SystemStateRow,
)
from .tunables import ALL_TUNABLES, NUMERIC_TUNABLES, SWITCH_TUNABLES, TunableParameter
from .vault import (
    CropVaultFrontmatter,
    DailyPlanVaultFrontmatter,
    DailyVaultFrontmatter,
    ForecastVaultFrontmatter,
    LessonsVaultFrontmatter,
    VaultFrontmatter,
)
from .views import (
    ClampActivity24h,
    DailyOscillation,
    DailyOscillationSummary,
    DewPointRiskRow,
    OverrideActivity24h,
    PlanAccuracy,
    PlannerPerformance,
    WaterBudgetRow,
)

__all__ = [
    "ALL_TUNABLES",
    "AlertAckPayload",
    "AlertAction",
    "AlertCategory",
    "AlertDisposition",
    "AlertEnvelope",
    "AlertLogRow",
    "APIStatus",
    "AlertResolvePayload",
    "AlertSeverity",
    "ClampActivity24h",
    "ClimateRow",
    "Conditions",
    "ConsumablesLog",
    "Crop",
    "CropAction",
    "CropCreate",
    "CropDetail",
    "CropEvent",
    "CropEventType",
    "CropHealthSummaryItem",
    "CropListItem",
    "CropRecentObservation",
    "CropStage",
    "CropTargetProfile",
    "CropUpdate",
    "CropVaultFrontmatter",
    "DailyOscillation",
    "DailyOscillationSummary",
    "DailyPlanVaultFrontmatter",
    "DailySummaryRow",
    "DailyVaultFrontmatter",
    "DataGap",
    "DataGapStatus",
    "DewPointRiskRow",
    "Diagnostics",
    "ESP32LogLevel",
    "ESP32LogRow",
    "EnergySample",
    "EquipmentStateEvent",
    "EventCreate",
    "ForecastActionLog",
    "ForecastActionRule",
    "ForecastActionType",
    "ForecastHour",
    "ForecastVaultFrontmatter",
    "HAEntityState",
    "Harvest",
    "HealthTrendPoint",
    "ImageObservation",
    "IrrigationLog",
    "IrrigationSchedule",
    "LabResult",
    "LessonAction",
    "LessonConfidence",
    "LessonCreate",
    "LessonUpdate",
    "LessonValidate",
    "LessonsVaultFrontmatter",
    "MaintenanceLog",
    "NUMERIC_TUNABLES",
    "Observation",
    "ObservationAction",
    "ObservationCreate",
    "ObservationType",
    "ObservationWithCrop",
    "OpenMeteoForecastResponse",
    "OpenMeteoHourly",
    "OverrideActivity24h",
    "OverrideEvent",
    "ParamRationale",
    "Plan",
    "PlanAccuracy",
    "PlanEvaluation",
    "PlanHypothesisStructured",
    "PlanId",
    "PlanJournalRow",
    "PlanSource",
    "PlanTransition",
    "PlannerLesson",
    "PlannerPerformance",
    "SWITCH_TUNABLES",
    "SensorRegistry",
    "SetpointChange",
    "SetpointClamp",
    "SetpointPlanRow",
    "SetpointSnapshot",
    "SetpointSource",
    "StressWindow",
    "SystemStateRow",
    "Treatment",
    "TunableParameter",
    "UtilityCategory",
    "UtilityCost",
    "VaultFrontmatter",
    "WaterBudgetRow",
    "ZoneDetail",
    "ZoneListItem",
    "ZoneObservation",
]
