"""changes

Revision ID: 001e786430d8
Revises: a6635b36f5b2
Create Date: 2025-07-30 10:11:42.998116

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '001e786430d8'
down_revision = 'a6635b36f5b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zonereading',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('zone_id', sa.Uuid(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('humidity', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['zone_id'], ['zone.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('greenhouseclimatehistory')
    op.drop_table('zoneclimatehistory')
    op.add_column('sensor', sa.Column('value', sa.Float(), nullable=True))
    op.drop_column('sensor', 'reading')
    op.add_column('zone', sa.Column('temperature', sa.Float(), nullable=True))
    op.add_column('zone', sa.Column('humidity', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('zone', 'humidity')
    op.drop_column('zone', 'temperature')
    op.add_column('sensor', sa.Column('reading', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('sensor', 'value')
    op.create_table('zoneclimatehistory',
    sa.Column('temperature', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('humidity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('zone_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['zone_id'], ['zone.id'], name='zoneclimatehistory_zone_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='zoneclimatehistory_pkey')
    )
    op.create_table('greenhouseclimatehistory',
    sa.Column('temperature', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('humidity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('greenhouse_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('outside_temperature', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('outside_humidity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['greenhouse_id'], ['greenhouse.id'], name='greenhouseclimatehistory_greenhouse_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='greenhouseclimatehistory_pkey')
    )
    op.drop_table('zonereading')
    # ### end Alembic commands ###
