"""openapi_v2_models

Revision ID: 0108966434fc
Revises: 643b9882529b
Create Date: 2025-08-15 12:28:22.977689

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0108966434fc'
down_revision = '643b9882529b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # PHASE 1: Create enum types first
    op.execute("CREATE TYPE sensorscope AS ENUM ('ZONE', 'GREENHOUSE', 'EXTERNAL')")
    op.execute("CREATE TYPE actuatorkind AS ENUM ('FAN', 'VENT', 'HEATER', 'COOLER', 'HUMIDIFIER', 'DEHUMIDIFIER', 'IRRIGATION', 'LIGHT')")
    op.execute("CREATE TYPE buttonkind AS ENUM ('EMERGENCY_STOP', 'TEMP_UP', 'TEMP_DOWN', 'HUMIDITY_UP', 'HUMIDITY_DOWN', 'OVERRIDE_30MIN')")

    # PHASE 2: Create new tables that don't depend on changes to existing tables

    # Create app_user table (rename from user)
    op.create_table('app_user',
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_user_email'), 'app_user', ['email'], unique=True)

    # Migrate data from user to app_user
    op.execute("""
        INSERT INTO app_user (id, email, is_active, is_superuser, full_name, hashed_password, created_at)
        SELECT id, email, is_active, is_superuser, full_name, hashed_password, created_at
        FROM "user"
    """)

    # Create idempotency_key table
    op.create_table('idempotency_key',
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('controller_id', sa.Uuid(), nullable=False),
    sa.Column('body_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=False),
    sa.Column('response_body', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )

    # PHASE 2: Update existing tables

    # Update greenhouse table
    op.add_column('greenhouse', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))  # nullable initially
    op.add_column('greenhouse', sa.Column('rails_max_temp_c', sa.Float(), nullable=False, server_default='50.0'))
    op.add_column('greenhouse', sa.Column('rails_min_temp_c', sa.Float(), nullable=False, server_default='-10.0'))
    op.add_column('greenhouse', sa.Column('params', sa.JSON(), nullable=True))
    op.add_column('greenhouse', sa.Column('user_id', sa.Uuid(), nullable=True))  # nullable initially

    # Copy title to name and owner_id to user_id
    op.execute("UPDATE greenhouse SET name = title")
    op.execute("UPDATE greenhouse SET user_id = owner_id")

    # Now make name and user_id non-nullable
    op.alter_column('greenhouse', 'name', nullable=False)
    op.alter_column('greenhouse', 'user_id', nullable=False)

    # Update foreign key constraint
    op.drop_constraint('greenhouse_owner_id_fkey', 'greenhouse', type_='foreignkey')
    op.create_foreign_key(None, 'greenhouse', 'app_user', ['user_id'], ['id'], ondelete='CASCADE')

    # Drop old columns
    op.drop_column('greenhouse', 'title')
    op.drop_column('greenhouse', 'owner_id')

    # Update controller table
    op.add_column('controller', sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=True))  # nullable initially
    op.add_column('controller', sa.Column('device_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))  # nullable initially
    op.add_column('controller', sa.Column('is_climate_controller', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('controller', sa.Column('fw_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('controller', sa.Column('hw_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('controller', sa.Column('last_seen', sa.DateTime(), nullable=True))

    # Copy name to label and generate device_name
    op.execute("UPDATE controller SET label = name")
    op.execute("""
        UPDATE controller SET device_name = 'verdify-' || LOWER(RIGHT(REPLACE(id::text, '-', ''), 6))
        WHERE device_name IS NULL
    """)

    # Make label and device_name non-nullable
    op.alter_column('controller', 'label', nullable=False)
    op.alter_column('controller', 'device_name', nullable=False)

    # Add unique constraints
    op.create_unique_constraint('uq_controller_device_name', 'controller', ['device_name'])
    op.create_unique_constraint('uq_greenhouse_climate_controller', 'controller', ['greenhouse_id', 'is_climate_controller'])
    op.drop_column('controller', 'name')

    # Update sensor table
    op.add_column('sensor', sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=True))  # nullable initially
    op.add_column('sensor', sa.Column('scope', postgresql.ENUM('ZONE', 'GREENHOUSE', 'EXTERNAL', name='sensorscope', create_type=False), nullable=True))  # nullable initially
    op.add_column('sensor', sa.Column('include_in_climate_loop', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('sensor', sa.Column('modbus_slave_id', sa.Integer(), nullable=True))
    op.add_column('sensor', sa.Column('modbus_reg', sa.Integer(), nullable=True))
    op.add_column('sensor', sa.Column('value_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('sensor', sa.Column('scale_factor', sa.Float(), nullable=False, server_default='1.0'))
    op.add_column('sensor', sa.Column('offset', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('sensor', sa.Column('poll_interval_s', sa.Integer(), nullable=False, server_default='10'))

    # Migrate type to kind and set default scope
    op.execute("UPDATE sensor SET kind = type::text")
    op.execute("UPDATE sensor SET scope = 'ZONE'")  # Default scope

    # Make kind and scope non-nullable
    op.alter_column('sensor', 'kind', nullable=False)
    op.alter_column('sensor', 'scope', nullable=False)

    op.drop_column('sensor', 'type')

    # PHASE 3: Create new tables that depend on updated tables

    op.create_table('config_snapshot',
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('etag', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('greenhouse_id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['greenhouse_id'], ['greenhouse.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('plan',
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('etag', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('greenhouse_id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['greenhouse_id'], ['greenhouse.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('state_machine_row',
    sa.Column('temp_stage', sa.Integer(), nullable=True),
    sa.Column('humi_stage', sa.Integer(), nullable=True),
    sa.Column('is_fallback', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('greenhouse_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['greenhouse_id'], ['greenhouse.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('controller_button',
    sa.Column('button_kind', postgresql.ENUM('EMERGENCY_STOP', 'TEMP_UP', 'TEMP_DOWN', 'HUMIDITY_UP', 'HUMIDITY_DOWN', 'OVERRIDE_30MIN', name='buttonkind', create_type=False), nullable=False),
    sa.Column('target_temp_stage', sa.Integer(), nullable=True),
    sa.Column('target_humi_stage', sa.Integer(), nullable=True),
    sa.Column('timeout_s', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('controller_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['controller_id'], ['controller.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('fan_group',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('controller_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['controller_id'], ['controller.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('state_machine_row_fan_group',
    sa.Column('row_id', sa.Uuid(), nullable=False),
    sa.Column('fan_group_id', sa.Uuid(), nullable=False),
    sa.Column('on_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fan_group_id'], ['fan_group.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['row_id'], ['state_machine_row.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('row_id', 'fan_group_id')
    )

    op.create_table('actuator',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kind', postgresql.ENUM('FAN', 'VENT', 'HEATER', 'COOLER', 'HUMIDIFIER', 'DEHUMIDIFIER', 'IRRIGATION', 'LIGHT', name='actuatorkind', create_type=False), nullable=False),
    sa.Column('relay_channel', sa.Integer(), nullable=True),
    sa.Column('min_on_ms', sa.Integer(), nullable=False),
    sa.Column('min_off_ms', sa.Integer(), nullable=False),
    sa.Column('fail_safe_state', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('controller_id', sa.Uuid(), nullable=False),
    sa.Column('zone_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['controller_id'], ['controller.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['zone_id'], ['zone.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('sensor_zone_map',
    sa.Column('sensor_id', sa.Uuid(), nullable=False),
    sa.Column('zone_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensor.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['zone_id'], ['zone.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('sensor_id', 'zone_id', 'kind')
    )

    op.create_table('fan_group_member',
    sa.Column('fan_group_id', sa.Uuid(), nullable=False),
    sa.Column('actuator_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['actuator_id'], ['actuator.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fan_group_id'], ['fan_group.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('fan_group_id', 'actuator_id')
    )

    op.create_table('state_machine_row_must_off',
    sa.Column('row_id', sa.Uuid(), nullable=False),
    sa.Column('actuator_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['actuator_id'], ['actuator.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['row_id'], ['state_machine_row.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('row_id', 'actuator_id')
    )

    op.create_table('state_machine_row_must_on',
    sa.Column('row_id', sa.Uuid(), nullable=False),
    sa.Column('actuator_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['actuator_id'], ['actuator.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['row_id'], ['state_machine_row.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('row_id', 'actuator_id')
    )

    # PHASE 4: Clean up old tables
    op.drop_index('ix_user_email', table_name='user')
    op.drop_table('user')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensor', sa.Column('type', postgresql.ENUM('TEMPERATURE', 'HUMIDITY', 'CO2', 'LIGHT', 'SOIL_MOISTURE', name='sensortype'), autoincrement=False, nullable=False))
    op.drop_column('sensor', 'poll_interval_s')
    op.drop_column('sensor', 'offset')
    op.drop_column('sensor', 'scale_factor')
    op.drop_column('sensor', 'value_type')
    op.drop_column('sensor', 'modbus_reg')
    op.drop_column('sensor', 'modbus_slave_id')
    op.drop_column('sensor', 'include_in_climate_loop')
    op.drop_column('sensor', 'scope')
    op.drop_column('sensor', 'kind')
    op.add_column('greenhouse', sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('greenhouse', sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'greenhouse', type_='foreignkey')
    op.create_foreign_key('greenhouse_owner_id_fkey', 'greenhouse', 'user', ['owner_id'], ['id'], ondelete='CASCADE')
    op.drop_column('greenhouse', 'user_id')
    op.drop_column('greenhouse', 'params')
    op.drop_column('greenhouse', 'rails_min_temp_c')
    op.drop_column('greenhouse', 'rails_max_temp_c')
    op.drop_column('greenhouse', 'name')
    op.add_column('controller', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint('uq_greenhouse_climate_controller', 'controller', type_='unique')
    op.drop_constraint('uq_controller_device_name', 'controller', type_='unique')
    op.drop_column('controller', 'last_seen')
    op.drop_column('controller', 'hw_version')
    op.drop_column('controller', 'fw_version')
    op.drop_column('controller', 'is_climate_controller')
    op.drop_column('controller', 'device_name')
    op.drop_column('controller', 'label')
    op.create_table('user',
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_superuser', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='user_pkey')
    )
    op.create_index('ix_user_email', 'user', ['email'], unique=True)
    op.drop_table('state_machine_row_must_on')
    op.drop_table('state_machine_row_must_off')
    op.drop_table('fan_group_member')
    op.drop_table('sensor_zone_map')
    op.drop_table('actuator')
    op.drop_table('state_machine_row_fan_group')
    op.drop_table('fan_group')
    op.drop_table('controller_button')
    op.drop_table('state_machine_row')
    op.drop_table('plan')
    op.drop_table('config_snapshot')
    op.drop_table('idempotency_key')
    op.drop_index(op.f('ix_app_user_email'), table_name='app_user')
    op.drop_table('app_user')
    # ### end Alembic commands ###
