"""add_created_at_to_controller

Revision ID: 15c9254bb092
Revises: 768902e59314
Create Date: 2025-08-15 14:31:15.434764

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '15c9254bb092'
down_revision = '768902e59314'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add created_at column as nullable first
    op.add_column('controller', sa.Column('created_at', sa.DateTime(), nullable=True))

    # Set default value for existing records
    op.execute("UPDATE controller SET created_at = CURRENT_TIMESTAMP WHERE created_at IS NULL")

    # Make column NOT NULL
    op.alter_column('controller', 'created_at', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('controller', 'created_at')
    # ### end Alembic commands ###
