"""Add crop models

Revision ID: 1b24db7aa5bc
Revises: 2b2789b3524c
Create Date: 2025-08-01 15:21:22.028532

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '1b24db7aa5bc'
down_revision = '2b2789b3524c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crop',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('expected_yield_per_sqm', sa.Float(), nullable=True),
    sa.Column('growing_days', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('recipe', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zonecrop',
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('final_yield', sa.Float(), nullable=True),
    sa.Column('area_sqm', sa.Float(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('crop_id', sa.Uuid(), nullable=False),
    sa.Column('zone_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['crop_id'], ['crop.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['zone_id'], ['zone.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zonecropobservation',
    sa.Column('observed_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('health_score', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('zone_crop_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['zone_crop_id'], ['zonecrop.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('zonecropobservation')
    op.drop_table('zonecrop')
    op.drop_table('crop')
    # ### end Alembic commands ###
