"""fix_observation_type_enum_mapping

Revision ID: 1ed0a4df0641
Revises: c03cb77a6e44
Create Date: 2025-08-16 21:45:20.357483

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '1ed0a4df0641'
down_revision = 'c03cb77a6e44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
