"""Remove unesecarry greenhouse feilds

Revision ID: 1fcc3b03fab0
Revises: 95c745e65778
Create Date: 2025-08-11 12:41:12.324819

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '1fcc3b03fab0'
down_revision = '95c745e65778'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('greenhouse', 'temperature')
    op.drop_column('greenhouse', 'type')
    op.drop_column('greenhouse', 'humidity')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('greenhouse', sa.Column('humidity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('greenhouse', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('greenhouse', sa.Column('temperature', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
