"""inital

Revision ID: 2b2789b3524c
Revises:
Create Date: 2025-07-31 16:25:01.512353

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '2b2789b3524c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('greenhouse',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('humidity', sa.Float(), nullable=False),
    sa.Column('outside_temperature', sa.Float(), nullable=False),
    sa.Column('outside_humidity', sa.Float(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('controller',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('greenhouse_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['greenhouse_id'], ['greenhouse.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipment',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('controller_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['controller_id'], ['controller.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sensor',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sa.Enum('TEMPERATURE', 'HUMIDITY', 'CO2', 'LIGHT', 'SOIL_MOISTURE', name='sensortype'), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('unit', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_mapped', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('controller_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['controller_id'], ['controller.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zone',
    sa.Column('zone_number', sa.Integer(), nullable=False),
    sa.Column('location', sa.Enum('N', 'NE', 'E', 'SE', 'S', 'SW', 'W', 'NW', name='locationenum'), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('greenhouse_id', sa.Uuid(), nullable=False),
    sa.Column('temperature_sensor_id', sa.Uuid(), nullable=True),
    sa.Column('humidity_sensor_id', sa.Uuid(), nullable=True),
    sa.Column('co2_sensor_id', sa.Uuid(), nullable=True),
    sa.Column('light_sensor_id', sa.Uuid(), nullable=True),
    sa.Column('soil_moisture_sensor_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['co2_sensor_id'], ['sensor.id'], ),
    sa.ForeignKeyConstraint(['greenhouse_id'], ['greenhouse.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['humidity_sensor_id'], ['sensor.id'], ),
    sa.ForeignKeyConstraint(['light_sensor_id'], ['sensor.id'], ),
    sa.ForeignKeyConstraint(['soil_moisture_sensor_id'], ['sensor.id'], ),
    sa.ForeignKeyConstraint(['temperature_sensor_id'], ['sensor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zonereading',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('zone_id', sa.Uuid(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('humidity', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['zone_id'], ['zone.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('zonereading')
    op.drop_table('zone')
    op.drop_table('sensor')
    op.drop_table('equipment')
    op.drop_table('controller')
    op.drop_table('greenhouse')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
