"""make_greenhouse_id_nullable_for_onboarding

Revision ID: 31edd1b109cb
Revises: c4854dd9ff9e
Create Date: 2025-08-15 12:44:06.337685

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '31edd1b109cb'
down_revision = 'c4854dd9ff9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('controller', 'greenhouse_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('controller', 'greenhouse_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
