"""Add controller device authentication fields

Revision ID: 32b1d6cb17d3
Revises: afccaf995645
Create Date: 2025-08-17 14:49:36.272870

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '32b1d6cb17d3'
down_revision = 'afccaf995645'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('controller', sa.Column('hardware_profile', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('controller', sa.Column('first_seen', sa.DateTime(), nullable=True))
    op.add_column('controller', sa.Column('claim_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('controller', sa.Column('claim_code_expires_at', sa.DateTime(), nullable=True))
    op.add_column('controller', sa.Column('device_token_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('controller', sa.Column('token_expires_at', sa.DateTime(), nullable=True))
    # Add boolean column with default value first
    op.add_column('controller', sa.Column('token_exchange_completed', sa.Boolean(), nullable=True))
    # Update all existing rows to have False for the new column
    op.execute("UPDATE controller SET token_exchange_completed = false WHERE token_exchange_completed IS NULL")
    # Now make the column non-nullable
    op.alter_column('controller', 'token_exchange_completed', nullable=False)
    op.add_column('controller', sa.Column('claimed_at', sa.DateTime(), nullable=True))
    op.add_column('controller', sa.Column('claimed_by', sa.Uuid(), nullable=True))
    op.drop_index('uq_plan_active_per_greenhouse', table_name='plan', postgresql_where='(is_active = true)')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_plan_active_per_greenhouse', 'plan', ['greenhouse_id'], unique=True, postgresql_where='(is_active = true)')
    op.drop_column('controller', 'claimed_by')
    op.drop_column('controller', 'claimed_at')
    op.drop_column('controller', 'token_exchange_completed')
    op.drop_column('controller', 'token_expires_at')
    op.drop_column('controller', 'device_token_hash')
    op.drop_column('controller', 'claim_code_expires_at')
    op.drop_column('controller', 'claim_code')
    op.drop_column('controller', 'first_seen')
    op.drop_column('controller', 'hardware_profile')
    # ### end Alembic commands ###
