"""Add RBAC tables for greenhouse sharing

Revision ID: 42200736b281
Revises: 32b1d6cb17d3
Create Date: 2025-08-17 15:12:17.792272

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '42200736b281'
down_revision = '32b1d6cb17d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('greenhouse_invite',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('greenhouse_id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'OPERATOR', name='greenhouserole'), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('invited_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REVOKED', 'EXPIRED', name='invitestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['greenhouse_id'], ['greenhouse.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invited_by_user_id'], ['app_user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('greenhouse_id', 'email', name='uq_greenhouse_invite_active'),
    sa.UniqueConstraint('token')
    )
    op.create_table('greenhouse_member',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('greenhouse_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'OPERATOR', name='greenhouserole'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['greenhouse_id'], ['greenhouse.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('greenhouse_id', 'user_id', name='uq_greenhouse_member')
    )
    op.create_index(op.f('ix_greenhouse_member_greenhouse_id'), 'greenhouse_member', ['greenhouse_id'], unique=False)
    op.create_index(op.f('ix_greenhouse_member_user_id'), 'greenhouse_member', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_greenhouse_member_user_id'), table_name='greenhouse_member')
    op.drop_index(op.f('ix_greenhouse_member_greenhouse_id'), table_name='greenhouse_member')
    op.drop_table('greenhouse_member')
    op.drop_table('greenhouse_invite')
    # ### end Alembic commands ###
