"""Model tweaks

Revision ID: 492a45d8184f
Revises: c071a01fbbf4
Create Date: 2025-08-13 10:12:12.711651

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '492a45d8184f'
down_revision = 'c071a01fbbf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claim_ticket',
    sa.Column('device_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('claim_code_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('device_name')
    )
    op.create_table('crop_template',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('expected_yield_per_sqm', sa.Float(), nullable=True),
    sa.Column('growing_days', sa.Integer(), nullable=True),
    sa.Column('recipe', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),  # FIX: was sa.NullType()
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('greenhouse',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('min_temp_c', sa.Float(), nullable=False),
    sa.Column('max_temp_c', sa.Float(), nullable=False),
    sa.Column('min_vpd_kpa', sa.Float(), nullable=False),
    sa.Column('max_vpd_kpa', sa.Float(), nullable=False),
    sa.Column('climate_baseline', sa.JSON(), nullable=False),
    sa.Column('site_pressure_hpa', sa.Float(), nullable=True),
    sa.Column('context_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('controller',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('greenhouse_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('device_name', sa.String(length=255), nullable=True),  # FIX: was sa.NullType()
    sa.Column('firmware', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('hardware_profile', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_climate_controller', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['greenhouse_id'], ['greenhouse.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_name')
    )
    op.create_index('ux_one_climate_controller', 'controller', ['greenhouse_id'], unique=True, postgresql_where=sa.text('is_climate_controller'))
    op.create_table('plan',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('greenhouse_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.DateTime(), nullable=False),
    sa.Column('effective_to', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['greenhouse_id'], ['greenhouse.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('greenhouse_id', 'version', name='uq_plan_version')
    )
    op.create_table('state_machine_row',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('greenhouse_id', sa.Uuid(), nullable=False),
    sa.Column('temp_stage', sa.Integer(), nullable=False),
    sa.Column('humi_stage', sa.Integer(), nullable=False),
    sa.Column('must_on_actuators', postgresql.ARRAY(sa.UUID()), server_default=sa.text('ARRAY[]::uuid[]'), nullable=False),
    sa.Column('must_off_actuators', postgresql.ARRAY(sa.UUID()), server_default=sa.text('ARRAY[]::uuid[]'), nullable=False),
    sa.Column('default_fan_on_count', sa.Integer(), nullable=True),
    sa.CheckConstraint('humi_stage BETWEEN -3 AND 3', name='ck_state_humi_stage'),
    sa.CheckConstraint('temp_stage BETWEEN -3 AND 3', name='ck_state_temp_stage'),
    sa.ForeignKeyConstraint(['greenhouse_id'], ['greenhouse.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('greenhouse_id', 'temp_stage', 'humi_stage', name='uq_state_machine_row')
    )
    op.create_table('controller_button',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('controller_id', sa.Uuid(), nullable=False),
    sa.Column('button_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('analog_channel', sa.Integer(), nullable=False),
    sa.Column('temp_stage', sa.Integer(), nullable=True),
    sa.Column('humi_stage', sa.Integer(), nullable=True),
    sa.Column('timeout_s', sa.Integer(), nullable=False),
    sa.CheckConstraint("button_type IN ('cool','humid','heat')", name='ck_button_type'),
    sa.CheckConstraint('humi_stage IS NULL OR humi_stage BETWEEN -3 AND 3', name='ck_humi_stage'),
    sa.CheckConstraint('temp_stage IS NULL OR temp_stage BETWEEN -3 AND 3', name='ck_temp_stage'),
    sa.ForeignKeyConstraint(['controller_id'], ['controller.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('controller_id', 'analog_channel', name='uq_controller_button_channel')
    )
    op.create_table('device_token',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('controller_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last4', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['controller_id'], ['controller.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('controller_id', 'revoked_at', deferrable='True', initially='IMMEDIATE', name='ux_one_active_token')
    )
    op.create_table('fan_group',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('controller_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['controller_id'], ['controller.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plan_setpoint',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('min_temp_c', sa.Float(), nullable=True),
    sa.Column('max_temp_c', sa.Float(), nullable=True),
    sa.Column('min_vpd_kpa', sa.Float(), nullable=True),
    sa.Column('max_vpd_kpa', sa.Float(), nullable=True),
    sa.Column('temp_delta_c', sa.Float(), nullable=True),
    sa.Column('humi_delta_pct', sa.Float(), nullable=True),
    sa.Column('vpd_delta_kpa', sa.Float(), nullable=True),
    sa.Column('temp_hysteresis_c', sa.Float(), nullable=True),
    sa.Column('humi_hysteresis_pct', sa.Float(), nullable=True),
    sa.Column('vpd_hysteresis_kpa', sa.Float(), nullable=True),
    sa.Column('stage_offset_temp', sa.Integer(), nullable=True),
    sa.Column('stage_offset_humi', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'ts', name='uq_plan_setpoint_ts')
    )
    op.create_table('sensor',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('controller_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scope', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('include_in_climate_loop', sa.Boolean(), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('poll_interval_s', sa.Integer(), nullable=True),
    sa.Column('modbus_slave_id', sa.Integer(), nullable=True),
    sa.Column('modbus_reg', sa.Integer(), nullable=True),
    sa.Column('scale_factor', sa.Float(), nullable=True),
    sa.Column('offset', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("scope IN ('zone','greenhouse','external')", name='ck_sensor_scope'),
    sa.ForeignKeyConstraint(['controller_id'], ['controller.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('state_machine_fan_rule',
    sa.Column('state_row_id', sa.Uuid(), nullable=False),
    sa.Column('fan_group_id', sa.Uuid(), nullable=False),
    sa.Column('on_count', sa.Integer(), nullable=False),
    sa.CheckConstraint('on_count >= 0', name='ck_fan_rule_on_count_nonneg'),
    sa.ForeignKeyConstraint(['fan_group_id'], ['fan_group.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['state_row_id'], ['state_machine_row.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('state_row_id', 'fan_group_id')
    )
    op.create_table('zone',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('greenhouse_id', sa.Uuid(), nullable=False),
    sa.Column('zone_number', sa.Integer(), nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('context_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('temperature_sensor_id', sa.Uuid(), nullable=True),
    sa.Column('humidity_sensor_id', sa.Uuid(), nullable=True),
    sa.Column('co2_sensor_id', sa.Uuid(), nullable=True),
    sa.Column('light_sensor_id', sa.Uuid(), nullable=True),
    sa.Column('soil_moisture_sensor_id', sa.Uuid(), nullable=True),
    sa.CheckConstraint("location IN ('N','NE','E','SE','S','SW','W','NW')", name='ck_zone_location'),
    sa.ForeignKeyConstraint(['co2_sensor_id'], ['sensor.id'], ),
    sa.ForeignKeyConstraint(['greenhouse_id'], ['greenhouse.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['humidity_sensor_id'], ['sensor.id'], ),
    sa.ForeignKeyConstraint(['light_sensor_id'], ['sensor.id'], ),
    sa.ForeignKeyConstraint(['soil_moisture_sensor_id'], ['sensor.id'], ),
    sa.ForeignKeyConstraint(['temperature_sensor_id'], ['sensor.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('greenhouse_id', 'zone_number', name='uq_zone_greenhouse_zone_number')
    )
    op.create_table('actuator',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('controller_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('relay_channel', sa.Integer(), nullable=True),
    sa.Column('min_on_ms', sa.Integer(), nullable=False),
    sa.Column('min_off_ms', sa.Integer(), nullable=False),
    sa.Column('fail_safe_state', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('zone_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("fail_safe_state IN ('on','off')", name='ck_actuator_fail_safe_state'),
    sa.ForeignKeyConstraint(['controller_id'], ['controller.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['zone_id'], ['zone.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crop',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('zone_id', sa.Uuid(), nullable=False),
    sa.Column('crop_template_id', sa.Uuid(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('final_yield', sa.Float(), nullable=True),
    sa.Column('area_sqm', sa.Float(), nullable=True),
    sa.CheckConstraint('end_date IS NULL OR end_date >= start_date', name='ck_crop_dates'),
    sa.ForeignKeyConstraint(['crop_template_id'], ['crop_template.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['zone_id'], ['zone.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ux_zone_crop_one_active', 'crop', ['zone_id'], unique=True, postgresql_where=sa.text('is_active'))
    op.create_table('plan_fertilization',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('zone_id', sa.Uuid(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('duration_s', sa.Integer(), nullable=False),
    sa.CheckConstraint('duration_s > 0', name='ck_fertilization_duration_positive'),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['zone_id'], ['zone.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'zone_id', 'ts', name='uq_plan_fertilization_ts')
    )
    op.create_table('plan_irrigation',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('zone_id', sa.Uuid(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('duration_s', sa.Integer(), nullable=False),
    sa.Column('fertilizer', sa.Boolean(), nullable=False),
    sa.Column('min_soil_vwc', sa.Float(), nullable=True),
    sa.CheckConstraint('duration_s > 0', name='ck_irrigation_duration_positive'),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['zone_id'], ['zone.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'zone_id', 'ts', name='uq_plan_irrigation_ts')
    )
    op.create_table('crop_observation',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('crop_id', sa.Uuid(), nullable=False),
    sa.Column('observed_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('health_score', sa.Integer(), nullable=True),
    sa.CheckConstraint('health_score IS NULL OR (health_score BETWEEN 1 AND 10)', name='ck_crop_obs_health'),
    sa.ForeignKeyConstraint(['crop_id'], ['crop.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fan_group_member',
    sa.Column('fan_group_id', sa.Uuid(), nullable=False),
    sa.Column('actuator_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['actuator_id'], ['actuator.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fan_group_id'], ['fan_group.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('fan_group_id', 'actuator_id')
    )
    op.create_table('plan_lighting',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('actuator_id', sa.Uuid(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('duration_s', sa.Integer(), nullable=False),
    sa.CheckConstraint('duration_s > 0', name='ck_lighting_duration_positive'),
    sa.ForeignKeyConstraint(['actuator_id'], ['actuator.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'actuator_id', 'ts', name='uq_plan_lighting_ts')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plan_lighting')
    op.drop_table('fan_group_member')
    op.drop_table('crop_observation')
    op.drop_table('plan_irrigation')
    op.drop_table('plan_fertilization')
    op.drop_index('ux_zone_crop_one_active', table_name='crop', postgresql_where=sa.text('is_active'))
    op.drop_table('crop')
    op.drop_table('actuator')
    op.drop_table('zone')
    op.drop_table('state_machine_fan_rule')
    op.drop_table('sensor')
    op.drop_table('plan_setpoint')
    op.drop_table('fan_group')
    op.drop_table('device_token')
    op.drop_table('controller_button')
    op.drop_table('state_machine_row')
    op.drop_table('plan')
    op.drop_index('ux_one_climate_controller', table_name='controller', postgresql_where=sa.text('is_climate_controller'))
    op.drop_table('controller')
    op.drop_table('greenhouse')
    op.drop_table('user')
    op.drop_table('crop_template')
    op.drop_table('claim_ticket')
    # ### end Alembic commands ###
