"""redesign_state_machine_models_to_match_spec

Revision ID: 52e718e4b837
Revises: a500c302750c
Create Date: 2025-08-16 20:33:40.241903

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '52e718e4b837'
down_revision = 'a500c302750c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('state_machine_fallback', sa.Column('must_on_actuators', sa.JSON(), nullable=False))
    op.add_column('state_machine_fallback', sa.Column('must_off_actuators', sa.JSON(), nullable=False))
    op.add_column('state_machine_fallback', sa.Column('must_on_fan_groups', sa.JSON(), nullable=False))
    op.add_column('state_machine_fallback', sa.Column('greenhouse_id', sa.Uuid(), nullable=False))
    op.create_unique_constraint(None, 'state_machine_fallback', ['greenhouse_id'])
    op.drop_constraint('state_machine_fallback_controller_id_fkey', 'state_machine_fallback', type_='foreignkey')
    op.create_foreign_key(None, 'state_machine_fallback', 'greenhouse', ['greenhouse_id'], ['id'], ondelete='CASCADE')
    op.drop_column('state_machine_fallback', 'fallback_action')
    op.drop_column('state_machine_fallback', 'controller_id')
    op.add_column('state_machine_row', sa.Column('temp_stage', sa.Integer(), nullable=True))
    op.add_column('state_machine_row', sa.Column('humi_stage', sa.Integer(), nullable=True))
    op.add_column('state_machine_row', sa.Column('is_fallback', sa.Boolean(), nullable=False))
    op.add_column('state_machine_row', sa.Column('must_on_actuators', sa.JSON(), nullable=False))
    op.add_column('state_machine_row', sa.Column('must_off_actuators', sa.JSON(), nullable=False))
    op.add_column('state_machine_row', sa.Column('must_on_fan_groups', sa.JSON(), nullable=False))
    op.add_column('state_machine_row', sa.Column('greenhouse_id', sa.Uuid(), nullable=False))
    op.create_unique_constraint('uq_smrow_gh_temp_humi', 'state_machine_row', ['greenhouse_id', 'temp_stage', 'humi_stage'])
    op.drop_constraint('state_machine_row_controller_id_fkey', 'state_machine_row', type_='foreignkey')
    op.create_foreign_key(None, 'state_machine_row', 'greenhouse', ['greenhouse_id'], ['id'], ondelete='CASCADE')
    op.drop_column('state_machine_row', 'controller_id')
    op.drop_column('state_machine_row', 'action_expr')
    op.drop_column('state_machine_row', 'condition_expr')
    op.drop_column('state_machine_row', 'row_index')
    op.drop_column('state_machine_row', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('state_machine_row', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('state_machine_row', sa.Column('row_index', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('state_machine_row', sa.Column('condition_expr', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('state_machine_row', sa.Column('action_expr', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('state_machine_row', sa.Column('controller_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'state_machine_row', type_='foreignkey')
    op.create_foreign_key('state_machine_row_controller_id_fkey', 'state_machine_row', 'controller', ['controller_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_smrow_gh_temp_humi', 'state_machine_row', type_='unique')
    op.drop_column('state_machine_row', 'greenhouse_id')
    op.drop_column('state_machine_row', 'must_on_fan_groups')
    op.drop_column('state_machine_row', 'must_off_actuators')
    op.drop_column('state_machine_row', 'must_on_actuators')
    op.drop_column('state_machine_row', 'is_fallback')
    op.drop_column('state_machine_row', 'humi_stage')
    op.drop_column('state_machine_row', 'temp_stage')
    op.add_column('state_machine_fallback', sa.Column('controller_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('state_machine_fallback', sa.Column('fallback_action', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'state_machine_fallback', type_='foreignkey')
    op.create_foreign_key('state_machine_fallback_controller_id_fkey', 'state_machine_fallback', 'controller', ['controller_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'state_machine_fallback', type_='unique')
    op.drop_column('state_machine_fallback', 'greenhouse_id')
    op.drop_column('state_machine_fallback', 'must_on_fan_groups')
    op.drop_column('state_machine_fallback', 'must_off_actuators')
    op.drop_column('state_machine_fallback', 'must_on_actuators')
    # ### end Alembic commands ###
