"""M1_M2: Add user email uniqueness constraint and plan partial unique index

Revision ID: 5c2ea57d6295
Revises: cc0eb28d66f3
Create Date: 2025-08-17 09:21:57.849847

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '5c2ea57d6295'
down_revision = 'cc0eb28d66f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # M1: User email uniqueness constraint
    op.drop_index('ix_app_user_email', table_name='app_user')
    op.create_index(op.f('ix_app_user_email'), 'app_user', ['email'], unique=False)
    op.create_unique_constraint('uq_user_email', 'app_user', ['email'])

    # M2: Partial unique index - only one active plan per greenhouse
    op.execute("""
        CREATE UNIQUE INDEX IF NOT EXISTS uq_plan_active_per_greenhouse
        ON plan (greenhouse_id)
        WHERE is_active = true
    """)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # M2: Drop partial unique index
    op.execute("DROP INDEX IF EXISTS uq_plan_active_per_greenhouse")

    # M1: Restore old user email index
    op.drop_constraint('uq_user_email', 'app_user', type_='unique')
    op.drop_index(op.f('ix_app_user_email'), table_name='app_user')
    op.create_index('ix_app_user_email', 'app_user', ['email'], unique=True)
    # ### end Alembic commands ###
