"""add created_at timestamps and greenhouse control parameters

Revision ID: 643b9882529b
Revises: 1fcc3b03fab0
Create Date: 2025-08-15 11:49:15.979758

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '643b9882529b'
down_revision = '1fcc3b03fab0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Add greenhouse columns as nullable first with default values
    op.add_column('greenhouse', sa.Column('min_temp_c', sa.Float(), nullable=True))
    op.add_column('greenhouse', sa.Column('max_temp_c', sa.Float(), nullable=True))
    op.add_column('greenhouse', sa.Column('min_vpd_kpa', sa.Float(), nullable=True))
    op.add_column('greenhouse', sa.Column('max_vpd_kpa', sa.Float(), nullable=True))
    op.add_column('greenhouse', sa.Column('enthalpy_open_kjkg', sa.Float(), nullable=True))
    op.add_column('greenhouse', sa.Column('enthalpy_close_kjkg', sa.Float(), nullable=True))
    op.add_column('greenhouse', sa.Column('site_pressure_hpa', sa.Float(), nullable=True))
    op.add_column('greenhouse', sa.Column('context_text', sqlmodel.sql.sqltypes.AutoString(length=4000), nullable=True))
    op.add_column('greenhouse', sa.Column('created_at', sa.DateTime(), nullable=True))

    # Update existing greenhouse records with default values
    op.execute("""
        UPDATE greenhouse SET
            min_temp_c = 15.0,
            max_temp_c = 30.0,
            min_vpd_kpa = 0.8,
            max_vpd_kpa = 1.5,
            enthalpy_open_kjkg = 50.0,
            enthalpy_close_kjkg = 40.0,
            site_pressure_hpa = 1013.25,
            created_at = NOW()
        WHERE min_temp_c IS NULL
    """)

    # Make greenhouse columns non-nullable
    op.alter_column('greenhouse', 'min_temp_c', nullable=False)
    op.alter_column('greenhouse', 'max_temp_c', nullable=False)
    op.alter_column('greenhouse', 'min_vpd_kpa', nullable=False)
    op.alter_column('greenhouse', 'max_vpd_kpa', nullable=False)
    op.alter_column('greenhouse', 'enthalpy_open_kjkg', nullable=False)
    op.alter_column('greenhouse', 'enthalpy_close_kjkg', nullable=False)
    op.alter_column('greenhouse', 'site_pressure_hpa', nullable=False)
    op.alter_column('greenhouse', 'created_at', nullable=False)

    # Drop old greenhouse columns
    op.drop_column('greenhouse', 'outside_temperature')
    op.drop_column('greenhouse', 'outside_humidity')

    # Add user created_at column as nullable first
    op.add_column('user', sa.Column('created_at', sa.DateTime(), nullable=True))

    # Update existing user records with current timestamp
    op.execute("UPDATE \"user\" SET created_at = NOW() WHERE created_at IS NULL")

    # Make user created_at column non-nullable
    op.alter_column('user', 'created_at', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'created_at')
    op.add_column('greenhouse', sa.Column('outside_humidity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('greenhouse', sa.Column('outside_temperature', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('greenhouse', 'created_at')
    op.drop_column('greenhouse', 'context_text')
    op.drop_column('greenhouse', 'site_pressure_hpa')
    op.drop_column('greenhouse', 'enthalpy_close_kjkg')
    op.drop_column('greenhouse', 'enthalpy_open_kjkg')
    op.drop_column('greenhouse', 'max_vpd_kpa')
    op.drop_column('greenhouse', 'min_vpd_kpa')
    op.drop_column('greenhouse', 'max_temp_c')
    op.drop_column('greenhouse', 'min_temp_c')
    # ### end Alembic commands ###
