"""Update zone crop schema and add observations table

Revision ID: 6902ec647fea
Revises: d8f135cc0754
Create Date: 2025-08-15 14:10:25.408282

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6902ec647fea'
down_revision = 'd8f135cc0754'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add new columns as nullable first
    op.add_column('zonecrop', sa.Column('planted_at', sa.DateTime(), nullable=True))
    op.add_column('zonecrop', sa.Column('harvested_at', sa.DateTime(), nullable=True))

    # Migrate data from old columns to new ones
    op.execute("UPDATE zonecrop SET planted_at = start_date WHERE planted_at IS NULL")
    op.execute("UPDATE zonecrop SET harvested_at = end_date WHERE harvested_at IS NULL AND end_date IS NOT NULL")

    # Make planted_at non-nullable
    op.alter_column('zonecrop', 'planted_at', nullable=False)

    # Drop old columns
    op.drop_column('zonecrop', 'end_date')
    op.drop_column('zonecrop', 'start_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add old columns as nullable first
    op.add_column('zonecrop', sa.Column('start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('zonecrop', sa.Column('end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))

    # Migrate data from new columns to old ones
    op.execute("UPDATE zonecrop SET start_date = planted_at WHERE start_date IS NULL")
    op.execute("UPDATE zonecrop SET end_date = harvested_at WHERE end_date IS NULL AND harvested_at IS NOT NULL")

    # Make start_date non-nullable
    op.alter_column('zonecrop', 'start_date', nullable=False)

    # Drop new columns
    op.drop_column('zonecrop', 'harvested_at')
    op.drop_column('zonecrop', 'planted_at')
    # ### end Alembic commands ###
