"""Removed is mapped

Revision ID: 73088fa7ea0e
Revises: d8b95efa304c
Create Date: 2025-08-03 14:02:55.732777

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '73088fa7ea0e'
down_revision = 'd8b95efa304c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sensor', 'is_mapped')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensor', sa.Column('is_mapped', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
