"""Add zone crop observation table

Revision ID: 768902e59314
Revises: 6902ec647fea
Create Date: 2025-08-15 14:12:07.415962

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '768902e59314'
down_revision = '6902ec647fea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
