"""Changes

Revision ID: 8c498a62ceb4
Revises: 492a45d8184f
Create Date: 2025-08-13 15:22:29.535697

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '8c498a62ceb4'
down_revision = '492a45d8184f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensor', sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('sensor', 'kind')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensor', sa.Column('kind', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('sensor', 'type')
    # ### end Alembic commands ###
