"""add_missing_uniqueness_constraints

Revision ID: 8c55168af50f
Revises: fc3c9eafddaa
Create Date: 2025-08-18 08:11:04.111402

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8c55168af50f'
down_revision = 'fc3c9eafddaa'
branch_labels = None
depends_on = None


def upgrade():
    # Add missing uniqueness constraints for data integrity

    # 1. Button Kind: unique per controller (controller_id, button_kind)
    op.create_unique_constraint(
        'uq_controller_button_kind',
        'controller_button',
        ['controller_id', 'button_kind']
    )

    # 2. Zone Number: unique per greenhouse (greenhouse_id, zone_number)
    op.create_unique_constraint(
        'uq_zone_number_per_greenhouse',
        'zone',
        ['greenhouse_id', 'zone_number']
    )

    # 3. Actuator Relay: unique per controller when not null (controller_id, relay_channel)
    op.create_unique_constraint(
        'uq_actuator_relay_per_controller',
        'actuator',
        ['controller_id', 'relay_channel']
    )

    # 4. Sensor Modbus: unique per controller (controller_id, modbus_slave_id, modbus_reg)
    op.create_unique_constraint(
        'uq_sensor_modbus_per_controller',
        'sensor',
        ['controller_id', 'modbus_slave_id', 'modbus_reg']
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('controller_button', 'button_kind',
               existing_type=postgresql.ENUM('COOL', 'HEAT', 'HUMID', name='buttonkind'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # Remove the unique constraints in reverse order

    # 4. Remove Sensor Modbus constraint
    op.drop_constraint('uq_sensor_modbus_per_controller', 'sensor', type_='unique')

    # 3. Remove Actuator Relay constraint
    op.drop_constraint('uq_actuator_relay_per_controller', 'actuator', type_='unique')

    # 2. Remove Zone Number constraint
    op.drop_constraint('uq_zone_number_per_greenhouse', 'zone', type_='unique')

    # 1. Remove Button Kind constraint
    op.drop_constraint('uq_controller_button_kind', 'controller_button', type_='unique')

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('controller_button', 'button_kind',
               existing_type=postgresql.ENUM('COOL', 'HEAT', 'HUMID', name='buttonkind'),
               nullable=True)
    # ### end Alembic commands ###
