"""Add last_seen to controller and make greenhouse_id nullable

Revision ID: 98d921bb1a84
Revises: 7a3e1e81a23e
Create Date: 2025-08-16 20:53:44.181764

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '98d921bb1a84'
down_revision = '7a3e1e81a23e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('controller', sa.Column('last_seen', sa.DateTime(), nullable=True))
    op.alter_column('controller', 'greenhouse_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('controller', 'greenhouse_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('controller', 'last_seen')
    # ### end Alembic commands ###
