"""L4: Add title field to Zone for sort compatibility

Revision ID: afccaf995645
Revises: 5c2ea57d6295
Create Date: 2025-08-17 09:47:36.961158

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'afccaf995645'
down_revision = '5c2ea57d6295'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # L4: Add title field to Zone
    op.add_column('zone', sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    # Note: uq_plan_active_per_greenhouse index preserved (not actually dropped)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # L4: Remove title field from Zone
    op.drop_column('zone', 'title')
    # Note: uq_plan_active_per_greenhouse index preserved (not actually recreated)
    # ### end Alembic commands ###
