"""add_observation_type_and_created_at_server_default

Revision ID: c03cb77a6e44
Revises: 98d921bb1a84
Create Date: 2025-08-16 21:32:14.987995

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c03cb77a6e44'
down_revision = '98d921bb1a84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the observation type enum with correct values
    op.execute("""
        CREATE TYPE observationtype AS ENUM (
            'growth', 'pest', 'disease', 'harvest', 'general'
        )
    """)

    op.add_column('zone_crop_observation', sa.Column('observation_type',
        postgresql.ENUM('growth', 'pest', 'disease', 'harvest', 'general', name='observationtype'),
        nullable=True))

    # Update created_at to have server default and timezone
    op.alter_column('zone_crop_observation', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               server_default=sa.func.now())
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove the observation_type column
    op.drop_column('zone_crop_observation', 'observation_type')

    # Drop the enum type
    op.execute("DROP TYPE observationtype")

    # Revert created_at back to simple timestamp
    op.alter_column('zone_crop_observation', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               server_default=None)
    # ### end Alembic commands ###
