"""add_onboarding_fields_to_controller

Revision ID: c4854dd9ff9e
Revises: c803f765db15
Create Date: 2025-08-15 12:39:29.969012

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c4854dd9ff9e'
down_revision = 'c803f765db15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('controller', sa.Column('claim_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('controller', sa.Column('device_token_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('controller', sa.Column('token_expires_at', sa.DateTime(), nullable=True))
    op.add_column('controller', sa.Column('hardware_profile', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('controller', sa.Column('firmware', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('controller', sa.Column('claimed_at', sa.DateTime(), nullable=True))
    op.add_column('controller', sa.Column('claimed_by', sa.Uuid(), nullable=True))
    op.add_column('controller', sa.Column('first_seen', sa.DateTime(), nullable=True))
    # Add boolean column with default value to handle existing rows
    op.add_column('controller', sa.Column('token_exchange_completed', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('controller', 'token_exchange_completed')
    op.drop_column('controller', 'first_seen')
    op.drop_column('controller', 'claimed_by')
    op.drop_column('controller', 'claimed_at')
    op.drop_column('controller', 'firmware')
    op.drop_column('controller', 'hardware_profile')
    op.drop_column('controller', 'token_expires_at')
    op.drop_column('controller', 'device_token_hash')
    op.drop_column('controller', 'claim_code')
    # ### end Alembic commands ###
