"""fix_idempotency_key_foreign_key

Revision ID: c803f765db15
Revises: 0108966434fc
Create Date: 2025-08-15 12:34:17.641272

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c803f765db15'
down_revision = '0108966434fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'idempotency_key', 'controller', ['controller_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'idempotency_key', type_='foreignkey')
    # ### end Alembic commands ###
