"""B4: make zonecrop crop_id NOT NULL per OpenAPI spec

Revision ID: cc0eb28d66f3
Revises: 1ed0a4df0641
Create Date: 2025-08-17 08:57:48.359011

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cc0eb28d66f3'
down_revision = '1ed0a4df0641'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zone_reading',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('zone_id', sa.Uuid(), nullable=False),
    sa.Column('reading_data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['zone_id'], ['zone.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('zonereading')
    op.alter_column('actuator', 'fail_safe_state',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('ON', 'OFF', name='failsafestate'),
               existing_nullable=False,
               postgresql_using='fail_safe_state::failsafestate')
    op.create_unique_constraint('uq_config_snapshot_greenhouse_version', 'config_snapshot', ['greenhouse_id', 'version'])
    op.create_unique_constraint('uq_controller_device_name', 'controller', ['device_name'])
    op.alter_column('sensor', 'value_type',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('FLOAT', 'INT', name='sensorvaluetype'),
               existing_nullable=True,
               postgresql_using='value_type::sensorvaluetype')
    op.add_column('state_machine_fallback', sa.Column('must_off_fan_groups', sa.JSON(), nullable=False))
    op.add_column('state_machine_row', sa.Column('must_off_fan_groups', sa.JSON(), nullable=False))
    op.add_column('zone', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.alter_column('zone_crop', 'crop_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint('zonecrop_crop_id_fkey', 'zone_crop', type_='foreignkey')
    op.create_foreign_key(None, 'zone_crop', 'crop', ['crop_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'zone_crop', type_='foreignkey')
    op.create_foreign_key('zonecrop_crop_id_fkey', 'zone_crop', 'crop', ['crop_id'], ['id'], ondelete='SET NULL')
    op.alter_column('zone_crop', 'crop_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('zone', 'is_active')
    op.drop_column('state_machine_row', 'must_off_fan_groups')
    op.drop_column('state_machine_fallback', 'must_off_fan_groups')
    op.alter_column('sensor', 'value_type',
               existing_type=sa.Enum('FLOAT', 'INT', name='sensorvaluetype'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_constraint('uq_controller_device_name', 'controller', type_='unique')
    op.drop_constraint('uq_config_snapshot_greenhouse_version', 'config_snapshot', type_='unique')
    op.alter_column('actuator', 'fail_safe_state',
               existing_type=sa.Enum('ON', 'OFF', name='failsafestate'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.create_table('zonereading',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('zone_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('reading_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['zone_id'], ['zone.id'], name='zonereading_zone_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='zonereading_pkey')
    )
    op.drop_table('zone_reading')
    # ### end Alembic commands ###
