"""additional crop changes

Revision ID: d8b95efa304c
Revises: 1b24db7aa5bc
Create Date: 2025-08-01 16:22:48.741381

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd8b95efa304c'
down_revision = '1b24db7aa5bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
