"""Add zone crops and observations

Revision ID: d8f135cc0754
Revises: 31edd1b109cb
Create Date: 2025-08-15 14:07:45.317231

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd8f135cc0754'
down_revision = '31edd1b109cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add title column as nullable first, set default values, then make it non-nullable
    op.add_column('greenhouse', sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))

    # Set default value for existing rows
    op.execute("UPDATE greenhouse SET title = name WHERE title IS NULL")

    # Now make it non-nullable
    op.alter_column('greenhouse', 'title', nullable=False)

    # Drop the old name column
    op.drop_column('greenhouse', 'name')

    # Add plan columns as nullable first, then set defaults and make non-nullable
    op.add_column('plan', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('plan', sa.Column('effective_from', sa.DateTime(), nullable=True))
    op.add_column('plan', sa.Column('effective_to', sa.DateTime(), nullable=True))

    # Set default values for existing plans
    op.execute("UPDATE plan SET is_active = false WHERE is_active IS NULL")
    op.execute("UPDATE plan SET effective_from = CURRENT_TIMESTAMP WHERE effective_from IS NULL")
    op.execute("UPDATE plan SET effective_to = CURRENT_TIMESTAMP + INTERVAL '1 year' WHERE effective_to IS NULL")

    # Make columns non-nullable
    op.alter_column('plan', 'is_active', nullable=False)
    op.alter_column('plan', 'effective_from', nullable=False)
    op.alter_column('plan', 'effective_to', nullable=False)

    op.create_unique_constraint('uq_plan_greenhouse_version', 'plan', ['greenhouse_id', 'version'])
    op.add_column('zone', sa.Column('context_text', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('zone', 'context_text')
    op.drop_constraint('uq_plan_greenhouse_version', 'plan', type_='unique')
    op.drop_column('plan', 'effective_to')
    op.drop_column('plan', 'effective_from')
    op.drop_column('plan', 'is_active')

    # Add back the name column
    op.add_column('greenhouse', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))

    # Copy title back to name
    op.execute("UPDATE greenhouse SET name = title WHERE name IS NULL")

    # Make name non-nullable
    op.alter_column('greenhouse', 'name', nullable=False)

    # Drop title column
    op.drop_column('greenhouse', 'title')
    # ### end Alembic commands ###
