"""add_idempotency_key_unique_constraint

Revision ID: dad914d4da09
Revises: f3c53e05f9d7
Create Date: 2025-08-15 16:57:24.773442

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'dad914d4da09'
down_revision = 'f3c53e05f9d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_idempotency_key_controller', 'idempotency_key', ['key', 'controller_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_idempotency_key_controller', 'idempotency_key', type_='unique')
    # ### end Alembic commands ###
