"""T17 state machine JSON columns and fallback table

Revision ID: f3c53e05f9d7
Revises: 842454810a57
Create Date: 2025-08-15 16:12:36.102750

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'f3c53e05f9d7'
down_revision = '842454810a57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('state_machine_fallback',
    sa.Column('must_on_actuators', sa.JSON(), nullable=False),
    sa.Column('must_off_actuators', sa.JSON(), nullable=False),
    sa.Column('must_on_fan_groups', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('greenhouse_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['greenhouse_id'], ['greenhouse.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('greenhouse_id')
    )
    op.drop_table('state_machine_row_must_off')
    op.drop_table('state_machine_row_fan_group')
    op.drop_table('state_machine_row_must_on')
    op.add_column('state_machine_row', sa.Column('must_on_actuators', sa.JSON(), nullable=False))
    op.add_column('state_machine_row', sa.Column('must_off_actuators', sa.JSON(), nullable=False))
    op.add_column('state_machine_row', sa.Column('must_on_fan_groups', sa.JSON(), nullable=False))
    op.create_unique_constraint('uq_state_machine_grid_position', 'state_machine_row', ['greenhouse_id', 'temp_stage', 'humi_stage', 'is_fallback'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_state_machine_grid_position', 'state_machine_row', type_='unique')
    op.drop_column('state_machine_row', 'must_on_fan_groups')
    op.drop_column('state_machine_row', 'must_off_actuators')
    op.drop_column('state_machine_row', 'must_on_actuators')
    op.create_table('state_machine_row_must_on',
    sa.Column('row_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('actuator_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['actuator_id'], ['actuator.id'], name='state_machine_row_must_on_actuator_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['row_id'], ['state_machine_row.id'], name='state_machine_row_must_on_row_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('row_id', 'actuator_id', name='state_machine_row_must_on_pkey')
    )
    op.create_table('state_machine_row_fan_group',
    sa.Column('row_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('fan_group_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('on_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['fan_group_id'], ['fan_group.id'], name='state_machine_row_fan_group_fan_group_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['row_id'], ['state_machine_row.id'], name='state_machine_row_fan_group_row_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('row_id', 'fan_group_id', name='state_machine_row_fan_group_pkey')
    )
    op.create_table('state_machine_row_must_off',
    sa.Column('row_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('actuator_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['actuator_id'], ['actuator.id'], name='state_machine_row_must_off_actuator_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['row_id'], ['state_machine_row.id'], name='state_machine_row_must_off_row_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('row_id', 'actuator_id', name='state_machine_row_must_off_pkey')
    )
    op.drop_table('state_machine_fallback')
    # ### end Alembic commands ###
