"""fix_button_kind_enum_to_use_constant_names

Revision ID: fc3c9eafddaa
Revises: 4c693f2ba5e0
Create Date: 2025-08-18 08:03:28.224119

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fc3c9eafddaa'
down_revision = '4c693f2ba5e0'
branch_labels = None
depends_on = None


def upgrade():
    # Fix ButtonKind enum to use constant names instead of values
    # Update enum values from lowercase ('cool', 'heat', 'humid') to uppercase ('COOL', 'HEAT', 'HUMID')

    # Create new enum type with uppercase values
    op.execute("CREATE TYPE buttonkind_new AS ENUM ('COOL', 'HEAT', 'HUMID')")

    # Add temporary column with new enum type
    op.execute("ALTER TABLE controller_button ADD COLUMN button_kind_new buttonkind_new")

    # Convert existing data
    op.execute("""
        UPDATE controller_button
        SET button_kind_new = CASE
            WHEN button_kind = 'cool' THEN 'COOL'::buttonkind_new
            WHEN button_kind = 'heat' THEN 'HEAT'::buttonkind_new
            WHEN button_kind = 'humid' THEN 'HUMID'::buttonkind_new
        END
    """)

    # Drop old column and rename new one
    op.execute("ALTER TABLE controller_button DROP COLUMN button_kind")
    op.execute("ALTER TABLE controller_button RENAME COLUMN button_kind_new TO button_kind")

    # Drop old enum type
    op.execute("DROP TYPE buttonkind")
    op.execute("ALTER TYPE buttonkind_new RENAME TO buttonkind")

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('greenhouse_invite', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('greenhouse_invite', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('greenhouse_invite', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.drop_index('ix_greenhouse_invite_expires_at', table_name='greenhouse_invite')
    op.drop_index('ix_greenhouse_invite_status_email', table_name='greenhouse_invite')
    op.drop_index('uq_greenhouse_invite_pending', table_name='greenhouse_invite', postgresql_where="(status = 'pending'::invitestatus)")
    op.alter_column('greenhouse_member', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.drop_index('uq_sensor_zone_kind', table_name='sensor_zone_map')
    # ### end Alembic commands ###


def downgrade():
    # Revert ButtonKind enum back to lowercase values

    # Create new enum type with lowercase values
    op.execute("CREATE TYPE buttonkind_new AS ENUM ('cool', 'heat', 'humid')")

    # Add temporary column with new enum type
    op.execute("ALTER TABLE controller_button ADD COLUMN button_kind_new buttonkind_new")

    # Convert existing data back
    op.execute("""
        UPDATE controller_button
        SET button_kind_new = CASE
            WHEN button_kind = 'COOL' THEN 'cool'::buttonkind_new
            WHEN button_kind = 'HEAT' THEN 'heat'::buttonkind_new
            WHEN button_kind = 'HUMID' THEN 'humid'::buttonkind_new
        END
    """)

    # Drop old column and rename new one
    op.execute("ALTER TABLE controller_button DROP COLUMN button_kind")
    op.execute("ALTER TABLE controller_button RENAME COLUMN button_kind_new TO button_kind")

    # Drop old enum type
    op.execute("DROP TYPE buttonkind")
    op.execute("ALTER TYPE buttonkind_new RENAME TO buttonkind")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_sensor_zone_kind', 'sensor_zone_map', ['zone_id', 'kind'], unique=True)
    op.alter_column('greenhouse_member', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.create_index('uq_greenhouse_invite_pending', 'greenhouse_invite', ['greenhouse_id', 'email'], unique=True, postgresql_where="(status = 'pending'::invitestatus)")
    op.create_index('ix_greenhouse_invite_status_email', 'greenhouse_invite', ['status', 'email'], unique=False)
    op.create_index('ix_greenhouse_invite_expires_at', 'greenhouse_invite', ['expires_at'], unique=False)
    op.alter_column('greenhouse_invite', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('greenhouse_invite', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('greenhouse_invite', 'expires_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    # ### end Alembic commands ###
