time-format %T
date-format %d/%b/%Y
log-format %h %^[%d:%t %^] "%r" %s %b "%R" "%u" %^ "%^" "%^" %^
html-report-title Verdify access analytics
real-time-html false
ignore-crawlers false
agent-list true
http-protocol yes
http-method yes
no-query-string true
with-output-resolver false
