/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignupImport } from './routes/signup'
import { Route as ResetPasswordImport } from './routes/reset-password'
import { Route as RecoverPasswordImport } from './routes/recover-password'
import { Route as LoginImport } from './routes/login'
import { Route as LayoutImport } from './routes/_layout'
import { Route as LayoutIndexImport } from './routes/_layout/index'
import { Route as GreenhousesGreenhouseIdImport } from './routes/greenhouses/$greenhouseId'
import { Route as LayoutSettingsImport } from './routes/_layout/settings'
import { Route as LayoutGreenhousesImport } from './routes/_layout/greenhouses'
import { Route as LayoutAdminImport } from './routes/_layout/admin'
import { Route as GreenhousesGreenhouseIdZonesImport } from './routes/greenhouses/$greenhouseId/zones'
import { Route as GreenhousesGreenhouseIdSettingsImport } from './routes/greenhouses/$greenhouseId/settings'
import { Route as GreenhousesGreenhouseIdGraphsImport } from './routes/greenhouses/$greenhouseId/graphs'
import { Route as GreenhousesGreenhouseIdControllerImport } from './routes/greenhouses/$greenhouseId/controller'
import { Route as GreenhousesGreenhouseIdClimateImport } from './routes/greenhouses/$greenhouseId/climate'

// Create/Update Routes

const SignupRoute = SignupImport.update({
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const ResetPasswordRoute = ResetPasswordImport.update({
  path: '/reset-password',
  getParentRoute: () => rootRoute,
} as any)

const RecoverPasswordRoute = RecoverPasswordImport.update({
  path: '/recover-password',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const GreenhousesGreenhouseIdRoute = GreenhousesGreenhouseIdImport.update({
  path: '/greenhouses/$greenhouseId',
  getParentRoute: () => rootRoute,
} as any)

const LayoutSettingsRoute = LayoutSettingsImport.update({
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutGreenhousesRoute = LayoutGreenhousesImport.update({
  path: '/greenhouses',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutAdminRoute = LayoutAdminImport.update({
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)

const GreenhousesGreenhouseIdZonesRoute =
  GreenhousesGreenhouseIdZonesImport.update({
    path: '/zones',
    getParentRoute: () => GreenhousesGreenhouseIdRoute,
  } as any)

const GreenhousesGreenhouseIdSettingsRoute =
  GreenhousesGreenhouseIdSettingsImport.update({
    path: '/settings',
    getParentRoute: () => GreenhousesGreenhouseIdRoute,
  } as any)

const GreenhousesGreenhouseIdGraphsRoute =
  GreenhousesGreenhouseIdGraphsImport.update({
    path: '/graphs',
    getParentRoute: () => GreenhousesGreenhouseIdRoute,
  } as any)

const GreenhousesGreenhouseIdControllerRoute =
  GreenhousesGreenhouseIdControllerImport.update({
    path: '/controller',
    getParentRoute: () => GreenhousesGreenhouseIdRoute,
  } as any)

const GreenhousesGreenhouseIdClimateRoute =
  GreenhousesGreenhouseIdClimateImport.update({
    path: '/climate',
    getParentRoute: () => GreenhousesGreenhouseIdRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/recover-password': {
      preLoaderRoute: typeof RecoverPasswordImport
      parentRoute: typeof rootRoute
    }
    '/reset-password': {
      preLoaderRoute: typeof ResetPasswordImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      preLoaderRoute: typeof SignupImport
      parentRoute: typeof rootRoute
    }
    '/_layout/admin': {
      preLoaderRoute: typeof LayoutAdminImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/greenhouses': {
      preLoaderRoute: typeof LayoutGreenhousesImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/settings': {
      preLoaderRoute: typeof LayoutSettingsImport
      parentRoute: typeof LayoutImport
    }
    '/greenhouses/$greenhouseId': {
      preLoaderRoute: typeof GreenhousesGreenhouseIdImport
      parentRoute: typeof rootRoute
    }
    '/_layout/': {
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
    '/greenhouses/$greenhouseId/climate': {
      preLoaderRoute: typeof GreenhousesGreenhouseIdClimateImport
      parentRoute: typeof GreenhousesGreenhouseIdImport
    }
    '/greenhouses/$greenhouseId/controller': {
      preLoaderRoute: typeof GreenhousesGreenhouseIdControllerImport
      parentRoute: typeof GreenhousesGreenhouseIdImport
    }
    '/greenhouses/$greenhouseId/graphs': {
      preLoaderRoute: typeof GreenhousesGreenhouseIdGraphsImport
      parentRoute: typeof GreenhousesGreenhouseIdImport
    }
    '/greenhouses/$greenhouseId/settings': {
      preLoaderRoute: typeof GreenhousesGreenhouseIdSettingsImport
      parentRoute: typeof GreenhousesGreenhouseIdImport
    }
    '/greenhouses/$greenhouseId/zones': {
      preLoaderRoute: typeof GreenhousesGreenhouseIdZonesImport
      parentRoute: typeof GreenhousesGreenhouseIdImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  LayoutRoute.addChildren([
    LayoutAdminRoute,
    LayoutGreenhousesRoute,
    LayoutSettingsRoute,
    LayoutIndexRoute,
  ]),
  LoginRoute,
  RecoverPasswordRoute,
  ResetPasswordRoute,
  SignupRoute,
  GreenhousesGreenhouseIdRoute.addChildren([
    GreenhousesGreenhouseIdClimateRoute,
    GreenhousesGreenhouseIdControllerRoute,
    GreenhousesGreenhouseIdGraphsRoute,
    GreenhousesGreenhouseIdSettingsRoute,
    GreenhousesGreenhouseIdZonesRoute,
  ]),
])

/* prettier-ignore-end */
