#!/usr/bin/env python3
"""Audit verdify.ai source content, build output, and Grafana embeds.

This is a validation gate for the Quartz website. It intentionally checks the
source vault and live Grafana, because Quartz builds can succeed while iframe
panel IDs are stale.
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
import time
from collections import Counter, defaultdict
from dataclasses import dataclass, field
from pathlib import Path
from urllib.parse import parse_qs, urlparse

DEFAULT_VAULT = Path("/mnt/iris/verdify-vault/website")
DEFAULT_PUBLIC = Path("/srv/verdify/verdify-site/public")
DEFAULT_IMAGE_MANIFEST = Path("docs/site-image-manifest.json")
DEFAULT_GRAFANA_CONTAINER = "verdify-grafana"
DEFAULT_SITE_CONTAINER = "verdify-site"
REBUILD_RETRY_ATTEMPTS = 25
REBUILD_RETRY_SLEEP_SEC = 2
BOX_DRAWING_RE = re.compile(r"[│┌└├─═╔]")

GENERATED_PAGES = {
    "forecast/index.md": "scripts/generate-forecast-page.py",
    "plans/index.md": "scripts/generate-plans-index.py",
    "greenhouse/lessons.md": "scripts/generate-lessons-page.py",
}
GENERATED_PREFIXES = {
    "plans/": "scripts/generate-daily-plan.py",
    "greenhouse/zones/": "scripts/render-zone-pages.py",
    "greenhouse/crops/": "scripts/render-crop-profiles.py",
}
GENERATED_EXCEPTIONS = {
    "greenhouse/zones/index.md",
    "greenhouse/zones/center.md",
    "greenhouse/crops/index.md",
}
GENERATED_PARTIALS = {
    "greenhouse/equipment.md": "scripts/render-equipment-page.py",
}


@dataclass(frozen=True)
class IframeRef:
    file: str
    line: int
    src: str
    dashboard_uid: str
    panel_id: str


@dataclass(frozen=True)
class ImageRef:
    file: str
    line: int
    ref: str


@dataclass(frozen=True)
class LinkRef:
    file: str
    line: int
    ref: str


@dataclass(frozen=True)
class SemanticIframe:
    file: str
    line: int
    heading: str
    dashboard_uid: str
    panel_id: str
    panel_title: str


@dataclass
class PageInfo:
    path: str
    title: str = ""
    description: str = ""
    noindex: bool = False
    tags: list[str] = field(default_factory=list)
    aliases: list[str] = field(default_factory=list)
    iframe_count: int = 0
    image_count: int = 0
    link_count: int = 0
    generated_by: str | None = None
    generated_marker: bool = False


@dataclass
class Finding:
    severity: str
    code: str
    message: str


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8", errors="replace")


def line_number(text: str, offset: int) -> int:
    return text.count("\n", 0, offset) + 1


def frontmatter(text: str) -> tuple[dict[str, object], str]:
    if not text.startswith("---\n"):
        return {}, text
    end = text.find("\n---", 4)
    if end == -1:
        return {}, text
    raw = text[4:end]
    body = text[end + 4 :]
    return parse_simple_yaml(raw), body


def parse_simple_yaml(raw: str) -> dict[str, object]:
    """Parse the small frontmatter subset needed for inventory."""
    data: dict[str, object] = {}
    current_key: str | None = None
    for line in raw.splitlines():
        if not line.strip():
            continue
        if line.startswith((" ", "\t")) and current_key:
            value = line.strip()
            if value.startswith("- "):
                existing = data.setdefault(current_key, [])
                if isinstance(existing, list):
                    existing.append(value[2:].strip().strip('"'))
            continue
        if ":" not in line:
            continue
        key, value = line.split(":", 1)
        key = key.strip()
        value = value.strip()
        current_key = key
        if value.startswith("[") and value.endswith("]"):
            data[key] = [item.strip().strip('"') for item in value[1:-1].split(",") if item.strip()]
        elif value:
            data[key] = value.strip().strip('"')
        else:
            data[key] = []
    return data


def generated_source(rel_path: str) -> str | None:
    if rel_path in GENERATED_PAGES:
        return GENERATED_PAGES[rel_path]
    if rel_path in GENERATED_PARTIALS:
        return GENERATED_PARTIALS[rel_path]
    if rel_path in GENERATED_EXCEPTIONS:
        return None
    for prefix, source in GENERATED_PREFIXES.items():
        if rel_path.startswith(prefix) and re.search(r"/\d{4}-\d{2}-\d{2}\.md$|/[^/]+\.md$", f"/{rel_path}"):
            return source
    return None


def has_generated_marker(text: str) -> bool:
    lowered = text.lower()
    markers = (
        "auto-generated",
        "generated by",
        "do not edit",
        "do not edit by hand",
        "rendered from db",
        "source of truth",
        "regenerate",
        "auto-render",
    )
    return any(marker in lowered for marker in markers)


def extract_iframes(rel_path: str, text: str) -> list[IframeRef]:
    refs: list[IframeRef] = []
    for match in re.finditer(r"<iframe\b[^>]*\bsrc=[\"']([^\"']+)[\"'][^>]*>", text, flags=re.IGNORECASE):
        src = match.group(1)
        parsed = urlparse(src)
        if parsed.netloc != "graphs.verdify.ai":
            continue
        parts = parsed.path.strip("/").split("/")
        if len(parts) < 2 or parts[0] != "d-solo":
            continue
        panel_id = parse_qs(parsed.query).get("panelId", [""])[0]
        refs.append(
            IframeRef(
                file=rel_path,
                line=line_number(text, match.start()),
                src=src,
                dashboard_uid=parts[1],
                panel_id=panel_id,
            )
        )
    return refs


def extract_images(rel_path: str, text: str) -> list[ImageRef]:
    refs: list[ImageRef] = []
    patterns = [
        r"!\[[^\]]*\]\(([^)]+)\)",
        r"<img\b[^>]*\bsrc=[\"']([^\"']+)[\"'][^>]*>",
        r"<meta\b[^>]*\b(?:property|name)=[\"'](?:og:image|twitter:image)[\"'][^>]*\bcontent=[\"']([^\"']+)[\"']",
    ]
    for pattern in patterns:
        for match in re.finditer(pattern, text, flags=re.IGNORECASE):
            ref = match.group(1).strip()
            if ref.startswith(("http://", "https://", "data:", "#", "mailto:")):
                continue
            refs.append(ImageRef(file=rel_path, line=line_number(text, match.start()), ref=ref))
    return refs


def extract_links(rel_path: str, text: str) -> list[LinkRef]:
    refs: list[LinkRef] = []
    patterns = [
        r"(?<!!)\[[^\]]+\]\(([^)]+)\)",
        r"<a\b[^>]*\bhref=[\"']([^\"']+)[\"'][^>]*>",
    ]
    for pattern in patterns:
        for match in re.finditer(pattern, text, flags=re.IGNORECASE):
            ref = match.group(1).strip()
            if should_skip_link(ref):
                continue
            refs.append(LinkRef(file=rel_path, line=line_number(text, match.start()), ref=ref))

    for match in re.finditer(r"\[\[([^\]|#]+)(?:#[^\]|]+)?(?:\|[^\]]+)?\]\]", text):
        ref = match.group(1).strip()
        if should_skip_link(ref):
            continue
        refs.append(LinkRef(file=rel_path, line=line_number(text, match.start()), ref=ref))
    return refs


def should_skip_link(ref: str) -> bool:
    return not ref or ref.startswith(("#", "http://", "https://", "mailto:", "tel:", "data:")) or ref.startswith("{")


def resolve_site_asset(vault_root: Path, rel_file: str, ref: str) -> Path:
    clean = ref.split("?", 1)[0].split("#", 1)[0]
    if clean.startswith("/"):
        return vault_root / clean.lstrip("/")
    return vault_root / rel_file / ".." / clean


def collect_pages(
    vault_root: Path,
) -> tuple[list[PageInfo], list[IframeRef], list[ImageRef], list[LinkRef], list[Finding]]:
    pages: list[PageInfo] = []
    iframes: list[IframeRef] = []
    images: list[ImageRef] = []
    links: list[LinkRef] = []
    findings: list[Finding] = []

    for path in sorted(vault_root.rglob("*.md")):
        rel_path = path.relative_to(vault_root).as_posix()
        text = read_text(path)
        replacement_count = text.count("\ufffd")
        if replacement_count:
            findings.append(
                Finding(
                    severity="warn",
                    code="replacement-character",
                    message=f"{rel_path} contains {replacement_count} Unicode replacement characters",
                )
            )
        fm, _body = frontmatter(text)
        page_iframes = extract_iframes(rel_path, text)
        page_images = extract_images(rel_path, text)
        page_links = extract_links(rel_path, text)
        source = generated_source(rel_path)
        marker = has_generated_marker(text)
        title = str(fm.get("title") or "")
        description = str(fm.get("description") or "")
        noindex = fm.get("noindex") is True or str(fm.get("noindex") or "").lower() == "true"
        tags = fm.get("tags") if isinstance(fm.get("tags"), list) else []
        aliases = fm.get("aliases") if isinstance(fm.get("aliases"), list) else []
        canonical_aliases = canonical_paths_for_page(rel_path)
        for alias in aliases:
            normalized_alias = normalize_route(str(alias))
            if normalized_alias in canonical_aliases:
                findings.append(
                    Finding(
                        severity="error",
                        code="self-alias",
                        message=f"{rel_path} aliases its own canonical route ({alias}); Quartz may emit a redirect stub",
                    )
                )
        if "```mermaid" in text:
            findings.append(
                Finding(
                    severity="error",
                    code="raw-mermaid",
                    message=f"{rel_path} contains a raw Mermaid block; use web-friendly HTML components instead",
                )
            )
        if BOX_DRAWING_RE.search(text):
            findings.append(
                Finding(
                    severity="error",
                    code="ascii-diagram",
                    message=f"{rel_path} contains box-drawing ASCII; use flow/floor-plan components instead",
                )
            )
        pages.append(
            PageInfo(
                path=rel_path,
                title=title,
                description=description,
                noindex=noindex,
                tags=[str(tag) for tag in tags],
                aliases=[str(alias) for alias in aliases],
                iframe_count=len(page_iframes),
                image_count=len(page_images),
                link_count=len(page_links),
                generated_by=source,
                generated_marker=marker,
            )
        )
        if source and not marker:
            findings.append(
                Finding(
                    severity="warn",
                    code="generated-marker-missing",
                    message=f"{rel_path} is produced by {source} but has no clear generated/source marker",
                )
            )
        if not noindex and not rel_path.startswith("plans/20"):
            if not title:
                findings.append(Finding("error", "seo-title-missing", f"{rel_path} has no frontmatter title"))
            elif len(title) < 18 and rel_path not in {"index.md"}:
                findings.append(
                    Finding(
                        "warn",
                        "seo-title-too-generic",
                        f"{rel_path} title is short/generic: {title!r}",
                    )
                )
            if not description:
                findings.append(
                    Finding("error", "seo-description-missing", f"{rel_path} has no frontmatter description")
                )
            elif len(description) < 80:
                findings.append(
                    Finding(
                        "warn",
                        "seo-description-short",
                        f"{rel_path} description is short ({len(description)} chars)",
                    )
                )
            elif len(description) > 220:
                findings.append(
                    Finding(
                        "warn",
                        "seo-description-long",
                        f"{rel_path} description is long ({len(description)} chars)",
                    )
                )
            if rel_path.startswith("plans/") and rel_path != "plans/index.md":
                findings.append(
                    Finding(
                        "error",
                        "seo-generated-plan-indexable",
                        f"{rel_path} is an individual generated daily plan and should be noindex",
                    )
                )
        iframes.extend(page_iframes)
        images.extend(page_images)
        links.extend(page_links)

    return pages, iframes, images, links, findings


def normalize_route(route: str) -> str:
    clean = route.split("?", 1)[0].split("#", 1)[0].strip()
    clean = clean.removeprefix("/")
    clean = clean.removesuffix("/")
    clean = clean.removesuffix(".html")
    clean = clean.removesuffix(".md")
    return clean or "index"


def canonical_paths_for_page(rel_path: str) -> set[str]:
    path = Path(rel_path)
    no_suffix = path.with_suffix("").as_posix()
    paths = {normalize_route(no_suffix)}
    if path.name == "index.md":
        parent = path.parent.as_posix()
        paths.add(normalize_route(parent if parent != "." else "index"))
    return paths


def load_image_manifest(path: Path) -> dict[str, dict[str, object]]:
    if not path.exists():
        return {}
    data = json.loads(path.read_text(encoding="utf-8"))
    images = data.get("images", {})
    return images if isinstance(images, dict) else {}


def check_images(
    vault_root: Path, images: list[ImageRef], image_manifest: dict[str, dict[str, object]]
) -> list[Finding]:
    findings: list[Finding] = []
    for image in images:
        resolved = resolve_site_asset(vault_root, image.file, image.ref).resolve()
        if not resolved.exists():
            findings.append(
                Finding(
                    severity="error",
                    code="missing-image",
                    message=f"{image.file}:{image.line} references missing image {image.ref}",
                )
            )
            continue
        if image.ref.startswith("/static/photos/"):
            filename = Path(image.ref).name
            entry = image_manifest.get(filename)
            if entry is None:
                findings.append(
                    Finding(
                        severity="error",
                        code="image-manifest-missing",
                        message=f"{image.file}:{image.line} references {filename}, which is not in docs/site-image-manifest.json",
                    )
                )
                continue
            if entry.get("status") != "approved":
                findings.append(
                    Finding(
                        severity="error",
                        code="image-not-approved",
                        message=f"{image.file}:{image.line} references {filename}, status={entry.get('status')}",
                    )
                )
            allowed_paths = entry.get("allowed_paths")
            if isinstance(allowed_paths, list) and allowed_paths:
                if not any(image.file == str(prefix) or image.file.startswith(str(prefix)) for prefix in allowed_paths):
                    findings.append(
                        Finding(
                            severity="error",
                            code="image-out-of-place",
                            message=f"{image.file}:{image.line} uses {filename} outside allowed paths: {', '.join(str(p) for p in allowed_paths)}",
                        )
                    )
    return findings


def resolve_internal_link(vault_root: Path, link: LinkRef) -> Path | None:
    clean = link.ref.split("?", 1)[0].split("#", 1)[0]
    if clean.endswith("/"):
        clean = clean.rstrip("/")
    if clean in ("", "."):
        return vault_root / "index.md"

    if clean.startswith("/"):
        rel = clean.lstrip("/")
        rel_candidates = [Path(rel)]
    else:
        rel_candidates = [Path(link.file).parent / clean, Path(clean)]

    candidates: list[Path] = []
    for rel_path in rel_candidates:
        if rel_path.suffix:
            candidates.append(vault_root / rel_path)
            if rel_path.suffix == ".html":
                candidates.append((vault_root / rel_path).with_suffix(".md"))
        else:
            candidates.extend(
                [
                    vault_root / rel_path / "index.md",
                    (vault_root / rel_path).with_suffix(".md"),
                ]
            )

    for candidate in candidates:
        if candidate.exists():
            return candidate
    return None


def check_links(vault_root: Path, links: list[LinkRef]) -> list[Finding]:
    findings: list[Finding] = []
    for link in links:
        if resolve_internal_link(vault_root, link) is None:
            findings.append(
                Finding(
                    severity="error",
                    code="missing-internal-link",
                    message=f"{link.file}:{link.line} links to missing page or asset {link.ref}",
                )
            )
    return findings


def docker_curl_json(container: str, path: str, timeout: int = 15) -> dict | list:
    result = subprocess.run(
        [
            "docker",
            "exec",
            container,
            "sh",
            "-c",
            f"curl -sS --max-time {timeout} http://localhost:3000{path}",
        ],
        capture_output=True,
        text=True,
        timeout=timeout + 5,
        check=False,
    )
    if result.returncode != 0:
        stderr = result.stderr.strip() or result.stdout.strip()
        raise RuntimeError(f"docker exec {container} curl {path} failed: {stderr}")
    return json.loads(result.stdout)


def dashboard_panel_titles(dashboard: dict) -> dict[str, str]:
    titles: dict[str, str] = {}

    def walk(items: list[dict] | None) -> None:
        for item in items or []:
            if item.get("type") == "row":
                walk(item.get("panels"))
            elif "id" in item:
                titles[str(item["id"])] = str(item.get("title") or "")

    walk(dashboard.get("panels"))
    return titles


def check_grafana(
    iframes: list[IframeRef],
    container: str,
) -> tuple[dict[str, set[str]], dict[str, dict[str, str]], list[Finding]]:
    findings: list[Finding] = []
    panel_ids_by_uid: dict[str, set[str]] = {}
    panel_titles_by_uid: dict[str, dict[str, str]] = {}
    for uid in sorted({iframe.dashboard_uid for iframe in iframes}):
        try:
            payload = docker_curl_json(container, f"/api/dashboards/uid/{uid}")
        except Exception as exc:
            findings.append(Finding("error", "grafana-fetch-failed", f"{uid}: {exc}"))
            panel_ids_by_uid[uid] = set()
            panel_titles_by_uid[uid] = {}
            continue
        dashboard = payload.get("dashboard") if isinstance(payload, dict) else None
        if not dashboard:
            findings.append(Finding("error", "grafana-dashboard-missing", f"dashboard UID {uid} not found"))
            panel_ids_by_uid[uid] = set()
            panel_titles_by_uid[uid] = {}
            continue
        panel_titles_by_uid[uid] = dashboard_panel_titles(dashboard)
        panel_ids_by_uid[uid] = set(panel_titles_by_uid[uid])

    for iframe in iframes:
        if not iframe.panel_id:
            findings.append(
                Finding(
                    "error",
                    "grafana-panel-missing",
                    f"{iframe.file}:{iframe.line} iframe has no panelId for dashboard {iframe.dashboard_uid}",
                )
            )
            continue
        if iframe.panel_id not in panel_ids_by_uid.get(iframe.dashboard_uid, set()):
            findings.append(
                Finding(
                    "error",
                    "grafana-panel-stale",
                    f"{iframe.file}:{iframe.line} references {iframe.dashboard_uid} panelId={iframe.panel_id}, which is not present live",
                )
            )
    return panel_ids_by_uid, panel_titles_by_uid, findings


def collect_semantic_iframes(
    vault_root: Path,
    iframes: list[IframeRef],
    panel_titles_by_uid: dict[str, dict[str, str]],
) -> list[SemanticIframe]:
    iframe_files = {iframe.file for iframe in iframes}
    headings_by_file: dict[str, list[tuple[int, str]]] = {}
    for rel_path in iframe_files:
        text = read_text(vault_root / rel_path)
        headings: list[tuple[int, str]] = []
        for offset, line in enumerate(text.splitlines(), start=1):
            match = re.match(r"^(#{1,4})\s+(.+)", line)
            if match:
                headings.append((offset, match.group(2).strip()))
        headings_by_file[rel_path] = headings

    semantic: list[SemanticIframe] = []
    for iframe in iframes:
        heading = ""
        for line, title in headings_by_file.get(iframe.file, []):
            if line <= iframe.line:
                heading = title
            else:
                break
        semantic.append(
            SemanticIframe(
                file=iframe.file,
                line=iframe.line,
                heading=heading,
                dashboard_uid=iframe.dashboard_uid,
                panel_id=iframe.panel_id,
                panel_title=panel_titles_by_uid.get(iframe.dashboard_uid, {}).get(iframe.panel_id, ""),
            )
        )
    return semantic


def check_public_output(vault_root: Path, public_root: Path) -> list[Finding]:
    findings: list[Finding] = []
    for _attempt in range(REBUILD_RETRY_ATTEMPTS):
        if public_root.exists() and (public_root / "index.html").is_file():
            break
        time.sleep(REBUILD_RETRY_SLEEP_SEC)
    if not public_root.exists():
        return [Finding("error", "public-missing", f"public output directory missing: {public_root}")]
    if not (public_root / "index.html").is_file():
        findings.append(Finding("error", "public-index-missing", f"missing built index.html in {public_root}"))

    source_pages = {path.relative_to(vault_root).with_suffix(".html").as_posix() for path in vault_root.rglob("*.md")}
    missing: list[str] = []
    for _attempt in range(REBUILD_RETRY_ATTEMPTS):
        missing = []
        for rel in sorted(source_pages):
            output = public_root / rel
            if rel == "index.html":
                output = public_root / "index.html"
            if not output.exists():
                missing.append(rel)
        if not missing:
            break
        time.sleep(REBUILD_RETRY_SLEEP_SEC)
    for rel in missing:
        findings.append(Finding("warn", "public-page-missing", f"source page has no built output: {rel}"))
    findings.extend(check_public_seo(public_root))
    return findings


def check_public_seo(public_root: Path) -> list[Finding]:
    findings: list[Finding] = []
    sitemap = public_root / "sitemap.xml"
    sitemap_text = read_text(sitemap) if sitemap.exists() else ""
    if not sitemap.exists():
        findings.append(Finding("error", "seo-sitemap-missing", f"missing sitemap.xml in {public_root}"))
    elif "tags/" in sitemap_text:
        findings.append(Finding("error", "seo-tags-in-sitemap", "tag pages are present in sitemap.xml"))

    for path in sorted(public_root.rglob("*.html")):
        rel = path.relative_to(public_root).as_posix()
        if rel == "404.html":
            continue
        text = read_text(path)
        is_redirect = 'http-equiv="refresh"' in text or "noindex" in text and "<p>Redirecting to" in text
        is_tag = rel.startswith("tags/")
        is_plan_detail = re.match(r"plans/\d{4}-\d{2}-\d{2}\.html$", rel) is not None
        robots_noindex = re.search(r'<meta\s+name=["\']robots["\'][^>]+content=["\'][^"\']*noindex', text, re.I)

        if is_tag and not robots_noindex:
            findings.append(Finding("error", "seo-tag-not-noindex", f"{rel} is a tag page without noindex"))
        if is_plan_detail and not robots_noindex:
            findings.append(
                Finding("error", "seo-plan-detail-not-noindex", f"{rel} is an individual plan page without noindex")
            )
        if is_redirect:
            continue

        h1_count = len(re.findall(r"<h1\b", text, flags=re.I))
        if not (is_tag or is_plan_detail) and h1_count != 1:
            findings.append(Finding("error", "seo-h1-count", f"{rel} has {h1_count} H1 elements"))

        desc = re.search(
            r'<meta\s+name=["\']description["\'][^>]+content=(["\'])(.*?)\1',
            text,
            re.I | re.S,
        )
        if not (is_tag or is_plan_detail) and (not desc or len(desc.group(2).strip()) < 80):
            findings.append(Finding("error", "seo-built-description", f"{rel} has missing/short meta description"))

    for match in re.finditer(r"https://verdify\.ai/plans/\d{4}-\d{2}-\d{2}", sitemap_text):
        findings.append(
            Finding("error", "seo-plan-detail-in-sitemap", f"individual plan URL appears in sitemap: {match.group(0)}")
        )
    return findings


def check_site_container(container: str) -> list[Finding]:
    result = None
    for _attempt in range(REBUILD_RETRY_ATTEMPTS):
        result = subprocess.run(
            [
                "docker",
                "exec",
                container,
                "sh",
                "-c",
                "test -r /usr/share/nginx/html/index.html && test -r /usr/share/nginx/html/404.html",
            ],
            capture_output=True,
            text=True,
            timeout=10,
            check=False,
        )
        if result.returncode == 0:
            return []
        time.sleep(REBUILD_RETRY_SLEEP_SEC)
    if result.returncode == 0:
        return []
    detail = (result.stderr or result.stdout).strip() or "index/404 unreadable"
    return [Finding("error", "site-container-bind-mount", f"{container} cannot read nginx html bind mount: {detail}")]


def print_summary(
    pages: list[PageInfo],
    iframes: list[IframeRef],
    images: list[ImageRef],
    links: list[LinkRef],
    panel_ids_by_uid: dict[str, set[str]],
    findings: list[Finding],
) -> None:
    severities = Counter(f.severity for f in findings)
    generated = [page for page in pages if page.generated_by]
    generated_missing = [page for page in generated if not page.generated_marker]
    print("Verdify site doctor")
    print(f"  pages: {len(pages)}")
    print(f"  generated or partial-generated pages: {len(generated)} ({len(generated_missing)} missing markers)")
    print(f"  grafana iframes: {len(iframes)} across {len({i.file for i in iframes})} pages")
    print(f"  grafana dashboards referenced: {len(panel_ids_by_uid)}")
    print(f"  local image refs: {len(images)}")
    print(f"  internal links: {len(links)}")
    print(f"  findings: {len(findings)} ({severities.get('error', 0)} errors, {severities.get('warn', 0)} warnings)")

    by_dashboard: dict[str, set[str]] = defaultdict(set)
    for iframe in iframes:
        by_dashboard[iframe.dashboard_uid].add(iframe.panel_id)
    if by_dashboard:
        print("\nGrafana embed inventory:")
        for uid in sorted(by_dashboard):
            live_count = len(panel_ids_by_uid.get(uid, set()))
            embedded = sorted(by_dashboard[uid], key=lambda value: int(value) if value.isdigit() else 10**9)
            print(f"  {uid}: {len(embedded)} embedded panel IDs, {live_count} live panels")

    if findings:
        print("\nFindings:")
        severity_order = {"error": 0, "warn": 1, "info": 2}
        for finding in sorted(findings, key=lambda f: (severity_order.get(f.severity, 9), f.code, f.message)):
            print(f"  [{finding.severity}] {finding.code}: {finding.message}")


def write_json_report(
    path: Path,
    pages: list[PageInfo],
    iframes: list[IframeRef],
    semantic_iframes: list[SemanticIframe],
    images: list[ImageRef],
    links: list[LinkRef],
    panel_ids_by_uid: dict[str, set[str]],
    findings: list[Finding],
) -> None:
    report = {
        "pages": [page.__dict__ for page in pages],
        "iframes": [iframe.__dict__ for iframe in iframes],
        "semantic_iframes": [iframe.__dict__ for iframe in semantic_iframes],
        "images": [image.__dict__ for image in images],
        "links": [link.__dict__ for link in links],
        "grafana": {
            uid: sorted(panel_ids, key=lambda value: int(value) if value.isdigit() else 10**9)
            for uid, panel_ids in panel_ids_by_uid.items()
        },
        "findings": [finding.__dict__ for finding in findings],
    }
    path.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def write_semantic_report(path: Path, semantic_iframes: list[SemanticIframe]) -> None:
    lines = [
        "# Verdify Site Grafana Semantic Inventory",
        "",
        "Each row maps a Markdown iframe to the nearest preceding heading and the live Grafana panel title.",
        "",
    ]
    current_file = ""
    for iframe in semantic_iframes:
        if iframe.file != current_file:
            current_file = iframe.file
            lines.extend(
                [
                    f"## {current_file}",
                    "",
                    "| Line | Heading | Dashboard | Panel | Live panel title |",
                    "|---:|---|---|---:|---|",
                ]
            )
        lines.append(
            f"| {iframe.line} | {iframe.heading or '-'} | {iframe.dashboard_uid} | "
            f"{iframe.panel_id or '-'} | {iframe.panel_title or 'MISSING'} |"
        )
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--vault-root", type=Path, default=DEFAULT_VAULT)
    parser.add_argument("--public-root", type=Path, default=DEFAULT_PUBLIC)
    parser.add_argument("--image-manifest", type=Path, default=DEFAULT_IMAGE_MANIFEST)
    parser.add_argument("--grafana-container", default=DEFAULT_GRAFANA_CONTAINER)
    parser.add_argument("--site-container", default=DEFAULT_SITE_CONTAINER)
    parser.add_argument("--skip-grafana", action="store_true")
    parser.add_argument("--skip-public", action="store_true")
    parser.add_argument("--skip-site-container", action="store_true")
    parser.add_argument("--json-report", type=Path, help="Write machine-readable report to this path")
    parser.add_argument(
        "--semantic-report",
        type=Path,
        help="Write a Markdown iframe-to-heading-to-live-panel-title inventory",
    )
    parser.add_argument("--warnings-fail", action="store_true", help="Exit nonzero on warnings as well as errors")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    findings: list[Finding] = []

    if not args.vault_root.exists():
        print(f"vault root missing: {args.vault_root}", file=sys.stderr)
        return 2

    image_manifest = load_image_manifest(args.image_manifest)
    pages, iframes, images, links, content_findings = collect_pages(args.vault_root)
    findings.extend(content_findings)
    findings.extend(check_images(args.vault_root, images, image_manifest))
    findings.extend(check_links(args.vault_root, links))

    panel_ids_by_uid: dict[str, set[str]] = {}
    panel_titles_by_uid: dict[str, dict[str, str]] = {}
    if not args.skip_grafana:
        panel_ids_by_uid, panel_titles_by_uid, grafana_findings = check_grafana(iframes, args.grafana_container)
        findings.extend(grafana_findings)

    if not args.skip_public:
        findings.extend(check_public_output(args.vault_root, args.public_root))

    if not args.skip_site_container:
        findings.extend(check_site_container(args.site_container))

    semantic_iframes = collect_semantic_iframes(args.vault_root, iframes, panel_titles_by_uid)

    print_summary(pages, iframes, images, links, panel_ids_by_uid, findings)
    if args.json_report:
        write_json_report(args.json_report, pages, iframes, semantic_iframes, images, links, panel_ids_by_uid, findings)
        print(f"\nJSON report written: {args.json_report}")
    if args.semantic_report:
        write_semantic_report(args.semantic_report, semantic_iframes)
        print(f"\nSemantic report written: {args.semantic_report}")

    has_errors = any(finding.severity == "error" for finding in findings)
    has_warnings = any(finding.severity == "warn" for finding in findings)
    if has_errors or (args.warnings_fail and has_warnings):
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
