#!/usr/bin/env /srv/greenhouse/.venv/bin/python3
"""Write harvest and treatment operation logs into the Verdify vault."""

from __future__ import annotations

import argparse
import asyncio
import os
import sys
from pathlib import Path

import asyncpg

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from verdify_schemas.operations import Harvest, Treatment  # noqa: E402

DEFAULT_OUT = Path("/mnt/iris/verdify-vault/operations")
DSN = os.environ.get(
    "VERDIFY_DSN",
    f"postgresql://verdify:{os.environ.get('POSTGRES_PASSWORD', 'verdify_tsdb_2026')}@127.0.0.1:5432/verdify",
)


def _fmt(value: object) -> str:
    return "—" if value in (None, "") else str(value)


def _data_table(rows: list[tuple[str, str, str]]) -> str:
    if not rows:
        return '<div class="metric-grid">\n  <div class="metric-card"><strong>No records</strong><p>No records have been logged yet.</p></div>\n</div>'
    lines = ['<div class="data-table">']
    for title, meta, body in rows:
        lines.append(f'  <div class="data-row"><strong>{title}</strong><span>{meta}</span><p>{body}</p></div>')
    lines.append("</div>")
    return "\n".join(lines)


async def render_harvests(conn: asyncpg.Connection) -> str:
    rows = await conn.fetch(
        """
        SELECT h.*, c.name AS crop_name, c.position AS crop_position
        FROM harvests h
        LEFT JOIN crops c ON c.id = h.crop_id
        ORDER BY h.ts DESC
        LIMIT 200
        """
    )
    rendered_rows = []
    for row in rows:
        harvest = Harvest.model_validate(dict(row))
        rendered_rows.append(
            (
                str(harvest.ts)[:16],
                f"{_fmt(row.get('crop_name'))} · {_fmt(harvest.zone)} · {_fmt(row.get('crop_position'))}",
                f"Weight {_fmt(harvest.weight_kg)} kg; count {_fmt(harvest.unit_count)}; grade {_fmt(harvest.quality_grade)}; revenue ${_fmt(harvest.revenue)}. {_fmt(harvest.notes)}",
            )
        )
    return "\n".join(
        [
            "---",
            "title: Harvest Log",
            "tags: [operations, harvests, auto-generated]",
            "---",
            "",
            "# Harvest Log",
            "",
            "> Auto-generated by `scripts/vault-operations-writer.py` from `harvests`.",
            "",
            _data_table(rendered_rows),
            "",
        ]
    )


async def render_treatments(conn: asyncpg.Connection) -> str:
    rows = await conn.fetch(
        """
        SELECT t.*, c.name AS crop_name, c.position AS crop_position
        FROM treatments t
        LEFT JOIN crops c ON c.id = t.crop_id
        ORDER BY t.ts DESC
        LIMIT 200
        """
    )
    rendered_rows = []
    for row in rows:
        treatment = Treatment.model_validate(dict(row))
        rendered_rows.append(
            (
                str(treatment.ts)[:16],
                f"{treatment.product} · {_fmt(treatment.zone)} · {_fmt(row.get('crop_name'))}",
                f"Method {_fmt(treatment.method)}; rate {_fmt(treatment.rate)} {_fmt(treatment.rate_unit)}; target {_fmt(treatment.target_pest)}; PHI {_fmt(treatment.phi_days)}d; REI {_fmt(treatment.rei_hours)}h. {_fmt(treatment.notes)}",
            )
        )
    return "\n".join(
        [
            "---",
            "title: Treatment Log",
            "tags: [operations, treatments, auto-generated]",
            "---",
            "",
            "# Treatment Log",
            "",
            "> Auto-generated by `scripts/vault-operations-writer.py` from `treatments`.",
            "",
            _data_table(rendered_rows),
            "",
        ]
    )


async def run(args: argparse.Namespace) -> int:
    out = Path(args.out)
    out.mkdir(parents=True, exist_ok=True)
    async with asyncpg.create_pool(DSN, min_size=1, max_size=2) as pool:
        async with pool.acquire() as conn:
            outputs = {
                "harvests.md": await render_harvests(conn),
                "treatments.md": await render_treatments(conn),
            }
    changes = 0
    for filename, content in outputs.items():
        target = out / filename
        old = target.read_text() if target.exists() else ""
        if old == content:
            print(f"UNCHANGED {target}")
            continue
        changes += 1
        if args.dry_run:
            print(f"WOULD WRITE {target}")
        else:
            target.write_text(content)
            print(f"WROTE {target}")
    print(f"{'Would change' if args.dry_run else 'Changed'} {changes} operation page(s)")
    return 0


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", default=str(DEFAULT_OUT))
    parser.add_argument("--dry-run", action="store_true")
    raise SystemExit(asyncio.run(run(parser.parse_args())))


if __name__ == "__main__":
    main()
